# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercouvr',
            name='date_val',
            field=models.DateField(blank=True, null=True),
        ),
    ]
