# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0002_dossiercouvr_date_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiercouvr',
            name='date_val_in',
        ),
        migrations.RemoveField(
            model_name='dossiercouvr',
            name='date_val_out',
        ),
    ]
