# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_auto_20171008_1015'),
        ('transfert', '0003_auto_20171008_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercouvr',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.TreasuryPosition'),
        ),
    ]
