# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0004_dossiercouvr_relevecmpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiercouvr',
            name='chk_ok',
        ),
        migrations.AddField(
            model_name='dossiercouvr',
            name='date_couvr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossiercouvr',
            name='date_val',
            field=models.DateField(blank=True, null=True, verbose_name='Date Pay'),
        ),
    ]
