# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0005_auto_20171008_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiercouvr',
            name='releveCmpt',
        ),
    ]
