# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0007_dossiercouvr_relevecmpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierctrl',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='dossierctrl',
            name='code_client',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='code_client',
        ),
        migrations.AlterField(
            model_name='dossierctrl',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
    ]
