# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0008_auto_20171009_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierctrl',
            name='code_client',
            field=models.CharField(default=99997, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virementctrl',
            name='code_client',
            field=models.CharField(default=99997, max_length=6),
            preserve_default=False,
        ),
    ]
