# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0009_auto_20171009_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierctrl',
            name='benef',
            field=models.CharField(help_text='Tapez le nom de b\xe9n\xe9ficiaire en cas de TRF et donneur en cas de RPT', max_length=200, verbose_name='B\xe9n\xe9ficiaire'),
        ),
        migrations.AlterField(
            model_name='dossierctrl',
            name='client',
            field=models.ForeignKey(help_text='Tapez le code client ici', on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
        migrations.AlterField(
            model_name='dossierctrl',
            name='code_client',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='benef',
            field=models.CharField(help_text='Tapez le nom de b\xe9n\xe9ficiaire en cas de TRF et donneur en cas de RPT', max_length=200, verbose_name='B\xe9n\xe9ficiaire'),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='client',
            field=models.ForeignKey(help_text='Tapez le code client ici', on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='code_client',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
