# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0010_auto_20171009_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiercouvr',
            name='msg_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_commission', to='settlement.SygmaCtrl'),
        ),
        migrations.AlterField(
            model_name='dossiercouvr',
            name='msg_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_payment', to='settlement.SygmaCtrl'),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='sygma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.SygmaCtrl'),
        ),
    ]
