# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0011_auto_20171012_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierctrl',
            name='bkdopi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfert.TrfDossierCouvrCtrl'),
        ),
    ]
