# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0013_auto_20171016_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierctrl',
            name='chk_fx',
            field=models.BooleanField(default=False, help_text='Cochez si la r\xe9servation des changes a \xe9t\xe9 confirm\xe9e le DMF et le client', verbose_name='R\xe9servation des changes'),
        ),
    ]
