# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0014_auto_20171022_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virementctrl',
            name='date_val',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
