# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0015_auto_20180110_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virementctrl',
            name='date_val',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
