# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0017_auto_20180110_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virementctrl',
            name='date_go',
            field=models.DateField(blank=True, null=True),
        ),
    ]
