# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_delete_cashflowdetailtwowayflowproxy'),
        ('transfert', '0018_auto_20180110_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierCouvrCashflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cashflow.cashflowdetail',),
        ),
        migrations.AddField(
            model_name='dossiercouvr',
            name='year_trd',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dossiercouvr',
            unique_together=set([('year_trd', 'ref_id')]),
        ),
    ]
