# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0019_auto_20180116_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DossierCtrlProxyBO',
        ),
        migrations.RemoveField(
            model_name='dossiercouvr',
            name='autorite',
        ),
        migrations.RemoveField(
            model_name='dossierctrl',
            name='autorite',
        ),
        migrations.RemoveField(
            model_name='dossierctrl',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='nature',
        ),
        migrations.AlterField(
            model_name='dossierctrl',
            name='chk_fx',
            field=models.BooleanField(default=False, help_text="Cochez si il s'agit d'un deal FxCli", verbose_name='FxCli'),
        ),
    ]
