# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0020_auto_20180323_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfdossierfx',
            name='ccy',
        ),
        migrations.RemoveField(
            model_name='trfdossierfx',
            name='clientCtrlFile',
        ),
        migrations.RemoveField(
            model_name='trfdossierfx',
            name='dossierCtrl',
        ),
        migrations.DeleteModel(
            name='TrfDossierFxProxyFO',
        ),
        migrations.DeleteModel(
            name='TrfDossierFx',
        ),
    ]
