# Generated by Django 2.1.2 on 2019-03-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0022_auto_20190318_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DossierCouvrCashflow',
        ),
    ]
