# Generated by Django 2.1.2 on 2019-03-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0024_auto_20190330_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierctrl',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Statut'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvrctrl',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Statut'),
        ),
        migrations.AlterField(
            model_name='virementctrl',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Statut'),
        ),
    ]
