# Generated by Django 2.1.2 on 2019-03-29 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0020_auto_20190330_0404'),
        ('tiers', '0024_auto_20190330_0412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0025_auto_20190330_0541'),
    ]
    operations = [
        migrations.RenameModel(
            old_name='DossierCtrl',
            new_name='TrfDossierCtrl',
        ),
        migrations.AlterField(
            model_name='trfdossierapurectrl',
            name='dossierCtrl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierapurectrl_dossier', to='transfert.TrfDossierCtrl'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvrctrl',
            name='dossierCtrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfert.TrfDossierCtrl'),
        ),
        migrations.AlterField(
            model_name='trfdossierincomplet',
            name='dossierCtrl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transfert.TrfDossierCtrl'),
        ),
    ]
