# Generated by Django 2.1.2 on 2019-03-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0026_auto_20190330_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_oper_approv', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_oper_verify', to=settings.AUTH_USER_MODEL, verbose_name='Contôleur'),
        ),
    ]
