# Generated by Django 2.1.2 on 2019-03-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0020_auto_20190330_0404'),
        ('interface', '0008_auto_20180322_0830'),
        ('transfert', '0028_auto_20190330_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrfDossierCouvrCtrl',
            new_name='TrfDossierExec',
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='account_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_account_couvr', to='tiers.AccountCorresp'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='account_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_account_pay', to='tiers.AccountCorresp'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ccy_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossiercouvr_ccy_couvr', to='util.Ccy'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ccy_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossiercouvr_ccy_pay', to='util.Ccy'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='corresp_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossiercouvr_corresp_couvr', to='tiers.Corresp'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='corresp_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossiercouvr_corresp_pay', to='tiers.Corresp'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_payment',
            field=models.ForeignKey(blank=True, limit_choices_to={'codtype': '/CODTYPTR/004'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_payment', to='settlement.SygmaCtrl'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Statut'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeProduct'),
        ),
    ]
