# Generated by Django 2.1.2 on 2019-03-29 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0024_auto_20190330_0412'),
        ('settlement', '0009_auto_20190330_0426'),
        ('util', '0020_auto_20190330_0404'),
        ('transfert', '0029_auto_20190330_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomDossierCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_verify', models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify')),
                ('time_verify', models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True)),
                ('chk_approv', models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv')),
                ('time_approv', models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True)),
                ('obs', models.TextField(blank=True, max_length=200, null=True)),
                ('code_banque', models.CharField(max_length=6, verbose_name='Code Banque')),
                ('date_ref', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant de domiciliation')),
                ('ref_di', models.CharField(max_length=15, unique=True, verbose_name='Ref de Déclaration')),
                ('date_di', models.DateField(verbose_name='Date de Déclaration')),
                ('no_inv', models.CharField(blank=True, max_length=20, null=True, verbose_name='Num. de Facture')),
                ('chk_pay', models.BooleanField(default=False, help_text='Cochez si la facture a été validée', verbose_name='Chk Pay')),
                ('date_pay', models.DateField(blank=True, help_text='Date de payment', null=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
                ('client', models.ForeignKey(help_text='Tapez le code client ici', on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl')),
                ('nature', models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeCommercial')),
                ('oper_approv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_approv', to=settings.AUTH_USER_MODEL)),
                ('oper_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('oper_verify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_verify', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_statut', to='util.Statut')),
            ],
            options={
                'verbose_name': 'DOM Dossier Manager',
                'verbose_name_plural': 'DOM Dossier Manager',
                'db_table': 'DOM_DOSSIER_CTRL',
                'ordering': ('-ref_di',),
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_commission',
            field=models.ForeignKey(blank=True, limit_choices_to={'codtype': '/CODTYPTR/018'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_commission', to='settlement.SygmaCtrl'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_exec',
            field=models.BooleanField(default=False, help_text='Système Encaissement/Décaissement', verbose_name='Check BO'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Correspondant Encaissement/Décaissement', verbose_name='Check CP'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='date_val',
            field=models.DateField(blank=True, help_text='MT950 Value Date', null=True, verbose_name='Value Date'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='type_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_l1': 'Transfert'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='trfdossierexec',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierexec_statut', to='util.Statut'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='dossier_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierDom', to='transfert.DomDossierCtrl', verbose_name='Dossier de Domiciliation'),
        ),
    ]
