# Generated by Django 2.1.2 on 2019-03-29 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0020_auto_20190330_0404'),
        ('settlement', '0009_auto_20190330_0426'),
        ('transfert', '0030_auto_20190330_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossiercouvr',
            options={'managed': True, 'verbose_name': 'Dossier TRF Couvr', 'verbose_name_plural': 'Dossier TRF Couvr'},
        ),
        migrations.AlterModelOptions(
            name='trfdossierctrl',
            options={'managed': True, 'verbose_name': 'TRF/RPT/VIR DossierCtrl', 'verbose_name_plural': 'TRF/RPT/VIR DossierCtrl'},
        ),
        migrations.AlterModelOptions(
            name='trfdossierexec',
            options={'managed': True, 'verbose_name': 'TRF Dossier Manager', 'verbose_name_plural': 'TRF Dossier Manager'},
        ),
        migrations.RenameField(
            model_name='trfdossierexec',
            old_name='dossierCtrl',
            new_name='trfDossier',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='account',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='benef',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='code_client',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='corresp',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='nomenclature',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='oper_cli',
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='nomenc_lv0',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_nomenc_lv0', to='util.CatalogTypeCommercial'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='pay_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_pay_msg', to='settlement.SygmaCtrl', verbose_name='Payment Message'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='trfdossierexec',
            name='date_exec_d',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trfdossierexec',
            name='date_val_d',
            field=models.DateField(blank=True, null=True),
        ),
    ]
