# Generated by Django 2.1.2 on 2019-03-29 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0020_auto_20190330_0404'),
        ('transfert', '0031_auto_20190330_0643'),
    ]

    operations = [
        #fake
        migrations.RenameField(
            model_name='trfdossiercouvr',
            old_name='oper_cli',
            new_name='oper_input',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='benef',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='chk_go',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='code_client',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='date_go',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='date_inv',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='nomenclature',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='oper_cli',
        ),
        #fake
        migrations.RemoveField(
            model_name='trfdossierexec',
            name='dossierCouvr',
        ),
        #fake
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        #fake
        migrations.AddField(
            model_name='trfdossierctrl',
            name='nomenc_lv1',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_nomenc_lv1', to='util.CatalogTypeCommercial'),
        ),
        #fake
        migrations.AddField(
            model_name='trfdossierctrl',
            name='oper_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        #fake
        migrations.AddField(
            model_name='trfdossierexec',
            name='trfDossierCouvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierexec_trfDossierCouvr', to='transfert.TrfDossierCouvr'),
        ),
        #fake
        migrations.AddField(
            model_name='virementctrl',
            name='nomenc_lv0',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_virementctrl_nomenc_lv0', to='util.CatalogTypeCommercial'),
        ),
    ]
