# Generated by Django 2.1.2 on 2019-03-29 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0020_auto_20190330_0404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0032_auto_20190330_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='virementctrl',
            name='nomenc_lv1',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_virementctrl_nomenc_lv1', to='util.CatalogTypeCommercial'),
        ),
        migrations.AddField(
            model_name='virementctrl',
            name='oper_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_virementctrl_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='bkdopi',
            field=models.OneToOneField(blank=True, help_text='Amplitude Record Reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_bkdopi', to='transfert.TrfDossierExec'),
        ),
        migrations.AlterField(
            model_name='trfdossierexec',
            name='trfDossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierexec_trfDossier', to='transfert.TrfDossierCtrl'),
        ),
    ]
