# Generated by Django 2.1.2 on 2019-03-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0033_auto_20190330_0708'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trfdossierexec',
            table='TRF_DOSSIER_EXEC',
        ),
    ]
