# Generated by Django 2.1.2 on 2019-03-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0034_auto_20190330_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptDossierCtrlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'RPT Dossier Ctrl.',
                'verbose_name_plural': 'RPT Dossier Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossierctrl',),
        ),
        migrations.CreateModel(
            name='RptDossierExec',
            fields=[
            ],
            options={
                'verbose_name': 'RPT Dossier Manager',
                'verbose_name_plural': 'RPT Dossier Manager',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossierexec',),
        ),
        migrations.CreateModel(
            name='TrfDossierCtrlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TRF Dossier Ctrl.',
                'verbose_name_plural': 'TRF Dossier Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossierctrl',),
        ),
        migrations.CreateModel(
            name='VirDossierCtrlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'VIR Dossier Ctrl.',
                'verbose_name_plural': 'VIR Dossier Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossierctrl',),
        ),
    ]
