# Generated by Django 2.1.2 on 2019-03-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0035_rptdossierctrlproxy_rptdossierexec_trfdossierctrlproxy_virdossierctrlproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virementctrl',
            name='ccy',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='client',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='nomenc_lv0',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='nomenc_lv1',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='oper_approv',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='oper_input',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='sygma',
        ),
        migrations.RemoveField(
            model_name='virementctrl',
            name='type_product',
        ),
        migrations.DeleteModel(
            name='VirementCtrl',
        ),
    ]
