# Generated by Django 2.1.2 on 2019-03-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0036_auto_20190330_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_statut', to='util.Statut'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_type_product', to='util.CatalogTypeProduct'),
        ),
    ]
