# Generated by Django 2.1.5 on 2019-03-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0037_auto_20190330_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domdossierctrl',
            table='dom_dossier_ctrl',
        ),
        migrations.AlterModelTable(
            name='trfdossierapure',
            table='trf_dossier_apure_detail',
        ),
        migrations.AlterModelTable(
            name='trfdossierapurectrl',
            table='trf_dossier_apure_ctrl',
        ),
        migrations.AlterModelTable(
            name='trfdossiercouvr',
            table='trf_dossier_couvr',
        ),
        migrations.AlterModelTable(
            name='trfdossierctrl',
            table='trf_dossier_ctrl',
        ),
        migrations.AlterModelTable(
            name='trfdossierexec',
            table='trf_dossier_exec',
        ),
        migrations.AlterModelTable(
            name='trfdossierincomplet',
            table='trf_dossier_incomplet',
        ),
    ]
