# Generated by Django 2.1.5 on 2019-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0038_auto_20190331_1620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierctrlfile',
            table='trf_dossier_ctrl_file',
        ),
    ]
