# Generated by Django 2.1.5 on 2019-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0040_auto_20190331_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='date_ref',
            field=models.DateField(blank=True, help_text='Date validation de déclaration', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterUniqueTogether(
            name='domdossierctrl',
            unique_together={('ref_di',)},
        ),
    ]
