# Generated by Django 2.1.5 on 2019-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0041_auto_20190401_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossierctrl',
            name='date_ap',
            field=models.DateField(blank=True, help_text="Date limite pour l'apurement", null=True, verbose_name='Date Limite'),
        ),
    ]
