# Generated by Django 2.1.5 on 2019-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0042_domdossierctrl_date_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant déclaré pour la domiciliation', max_digits=18, verbose_name='Montant dom.'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ref_di',
            field=models.CharField(help_text='Réf distribuée par MINFI/GUOT ou Banque Centrale', max_length=15, unique=True, verbose_name='Réf de Déclaration'),
        ),
    ]
