# Generated by Django 2.1.5 on 2019-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0043_auto_20190402_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ref_di',
            field=models.CharField(help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=15, unique=True, verbose_name='Réf décl'),
        ),
    ]
