# Generated by Django 2.1.5 on 2019-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0044_auto_20190402_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
