# Generated by Django 2.1.5 on 2019-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0046_auto_20190404_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredocDossierCtrlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'CREDOC Dossier Ctrl.',
                'verbose_name_plural': 'CREDOC Dossier Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossierctrl',),
        ),
        migrations.AlterField(
            model_name='trfdossierexec',
            name='ctrl',
            field=models.BooleanField(db_column='CTRL', default=False, help_text='Check rapprochement', verbose_name='ctrl'),
        ),
    ]
