# Generated by Django 2.1.5 on 2019-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0048_auto_20190418_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_creation',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Création', null=True),
        ),
    ]
