# Generated by Django 2.1.5 on 2019-05-29 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0049_trfdossierctrl_time_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_exp',
            field=models.BooleanField(default=False, help_text='Sending Agent', verbose_name='Chk Exp'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Receiving Agent', verbose_name='Chk Receive'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='oper_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_exp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='oper_recv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_recv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_exp',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True),
        ),
    ]
