# Generated by Django 2.1.5 on 2019-05-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0050_auto_20190529_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='chk_exp',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='chk_recv',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='oper_exp',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='oper_recv',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='time_exp',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='time_recv',
        ),
    ]
