# Generated by Django 2.1.5 on 2019-05-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0051_auto_20190529_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_statut', to='util.Statut'),
        ),
    ]
