# Generated by Django 2.1.5 on 2019-05-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0053_trfdossierctrl_doctracelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_docTraceLog', to='util.DocTraceLog'),
        ),
    ]
