# Generated by Django 2.1.5 on 2019-05-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0054_auto_20190531_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trfdossierctrl',
            old_name='time_creation',
            new_name='time_create',
        ),
    ]
