# Generated by Django 2.1.5 on 2019-05-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0055_auto_20190531_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='time_create',
        ),
    ]
