# Generated by Django 2.1.5 on 2019-05-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0056_remove_trfdossierctrl_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='date_saisie',
        ),
    ]
