# Generated by Django 2.1.5 on 2019-06-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0034_auto_20190604_0909'),
        ('transfert', '0057_remove_trfdossierctrl_date_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossierctrl',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_docTraceLog', to='util.DocTraceLog'),
        ),
    ]
