# Generated by Django 2.1.5 on 2019-07-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0059_trfdossierctrl_dossier_couvr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='oper_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
    ]
