# Generated by Django 2.1.5 on 2019-07-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0060_auto_20190701_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossiercouvr',
            options={'managed': True, 'verbose_name': 'BEAC Rétrocession/Couverture', 'verbose_name_plural': 'BEAC Rétrocession/Couverture'},
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='cpty',
            field=models.CharField(blank=True, default=None, help_text="Bénéficiaire pour TRF/Donneur d'ordre pour RPT ", max_length=100, null=True, verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_couvr',
            field=models.BooleanField(default=False, help_text='Check Flux Entrant/Sortant FX', verbose_name='Check Flux FX'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Check Flux Entrant/Sortant F.CFA', verbose_name='Check Flux F.CFA'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_couvr',
            field=models.DateField(blank=True, help_text='Date du Paiement/Réception FX', null=True, verbose_name='Date FX'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_val',
            field=models.DateField(blank=True, help_text='Date du Paiement/Réception F.CFA', null=True, verbose_name='Date F.CFA'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_couvr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du Paiement/Réception FX', max_digits=18, null=True, verbose_name='Montant FX'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_payment',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant du Paiement/Réception F.CFA', max_digits=18, null=True, verbose_name='Montant F.CFA'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_payment',
            field=models.ForeignKey(blank=True, help_text='Msg du Paiement/Réception F.CFA', limit_choices_to={'codtype': '/CODTYPTR/004'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_payment', to='settlement.SygmaCtrl', verbose_name='Msg F.CFA'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, help_text='Msg du Paiement/Réception FX', null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.TreasuryPosition', verbose_name='Msg FX'),
        ),
    ]
