# Generated by Django 2.1.5 on 2019-08-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0061_auto_20190704_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='ref_inv',
            field=models.TextField(blank=True, help_text="Remplissez toutes no. de factures s'il y en a plusieur et les séparez par ';' ", null=True, verbose_name='Réf. des factures'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_exec',
            field=models.BooleanField(default=False, help_text='Système Encaissement/Décaissement', verbose_name='Exécution'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Correspondant Encaissement/Décaissement', verbose_name='Corresp'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='dossier_couvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierCouvr', to='transfert.TrfDossierCouvr', verbose_name='BEAC'),
        ),
    ]
