# Generated by Django 2.1.5 on 2019-08-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0062_auto_20190812_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_commission', to='settlement.SygmaCtrl'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_payment',
            field=models.ForeignKey(blank=True, help_text='Msg du Paiement/Réception F.CFA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_payment', to='settlement.SygmaCtrl', verbose_name='Msg F.CFA'),
        ),
    ]
