# Generated by Django 2.1.5 on 2019-08-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0063_auto_20190813_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptDossierRtrocProxy',
            fields=[
            ],
            options={
                'verbose_name': 'BEAC RTROC Ctrl.',
                'verbose_name_plural': 'BEAC RTROC Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossiercouvr',),
        ),
        migrations.CreateModel(
            name='TrfDossierCouvrProxy',
            fields=[
            ],
            options={
                'verbose_name': 'BEAC COUVR Ctrl.',
                'verbose_name_plural': 'BEAC COUVR Ctrl.',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.trfdossiercouvr',),
        ),
        migrations.AlterModelOptions(
            name='trfdossiercouvr',
            options={'managed': True, 'verbose_name': 'BEAC RTROC/COUVR', 'verbose_name_plural': 'BEAC RTROC/COUVR'},
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text="Cochez si l'ensemble des transactions liée soient exécutées", verbose_name='FIN'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_commission',
            field=models.BooleanField(default=False, help_text='Check paiement de commission', verbose_name='FEE'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_couvr',
            field=models.BooleanField(default=False, help_text='Check Flux Entrant', verbose_name='COUVR'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Check Flux Sortant', verbose_name='PAY'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_couvr',
            field=models.DateField(blank=True, help_text='Date du flux Entrant', null=True, verbose_name='Date Couvr'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_val',
            field=models.DateField(blank=True, help_text='Date du flux Sortant', null=True, verbose_name='Date Pay'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_couvr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du flux Entrant', max_digits=18, null=True, verbose_name='Montant Entrant'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_out',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_payment',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant du flux Sortant', max_digits=18, null=True, verbose_name='Montant Sortant'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_commission',
            field=models.ForeignKey(blank=True, help_text='Msg Sygma de la commission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_commission', to='settlement.SygmaCtrl', verbose_name='Msg Commission'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='msg_payment',
            field=models.ForeignKey(blank=True, help_text='Msg Sygma de la contrevaleur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_msg_payment', to='settlement.SygmaCtrl', verbose_name='Msg Sygma'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, help_text='Msg MT950', null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.TreasuryPosition', verbose_name='MT950'),
        ),
    ]
