# Generated by Django 2.1.5 on 2019-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0065_trfdossierctrl_ref_swift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierctrlfile',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='trfdossierapure',
            name='ccy',
        ),
        migrations.RemoveField(
            model_name='trfdossierapure',
            name='trfDossierApureCtrl',
        ),
        migrations.RemoveField(
            model_name='trfdossierapurectrl',
            name='dossierCtrl',
        ),
        migrations.RemoveField(
            model_name='trfdossierapurectrl',
            name='oper_decl',
        ),
        migrations.RemoveField(
            model_name='trfdossierapurectrl',
            name='oper_examen',
        ),
        migrations.RemoveField(
            model_name='trfdossierapurectrl',
            name='oper_recall',
        ),
        migrations.RemoveField(
            model_name='trfdossierapurectrl',
            name='trfdossierapure_ptr',
        ),
        migrations.RemoveField(
            model_name='trfdossierincomplet',
            name='dossierCtrl',
        ),
        migrations.RemoveField(
            model_name='trfdossierincomplet',
            name='oper_appro',
        ),
        migrations.RemoveField(
            model_name='trfdossierincomplet',
            name='oper_ok',
        ),
        migrations.DeleteModel(
            name='DossierCtrlFile',
        ),
        migrations.DeleteModel(
            name='TrfDossierApure',
        ),
        migrations.DeleteModel(
            name='TrfDossierApureCtrl',
        ),
        migrations.DeleteModel(
            name='TrfDossierIncomplet',
        ),
    ]
