# Generated by Django 2.1.5 on 2019-08-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0067_auto_20190826_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossierapurectrl',
            options={'managed': True, 'verbose_name': 'Dossier Apurement Ctrl.', 'verbose_name_plural': 'Dossier Apurement Ctrl.'},
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossierctrl_ccy', to='util.Ccy', verbose_name='Ccy'),
        ),
    ]
