# Generated by Django 2.1.5 on 2019-08-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0037_auto_20190826_0814'),
        ('transfert', '0068_auto_20190826_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Local'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Taux de changes Fixing ECB', max_digits=8, null=True, verbose_name='Taux de convertion'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='montant_lc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='Montant Local'),
        ),
    ]
