# Generated by Django 2.1.5 on 2019-08-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0069_auto_20190826_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='montant_lc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant équivalent en F.CFA', max_digits=18, verbose_name='Montant Local'),
            preserve_default=False,
        ),
    ]
