# Generated by Django 2.1.5 on 2019-08-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0037_auto_20190826_0814'),
        ('transfert', '0070_auto_20190826_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossierctrl',
            name='chk_ap',
            field=models.BooleanField(default=False, help_text='Apurement requis', verbose_name='Chk Apure'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(blank=True, help_text='F.CFA pour le région CEMAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Local'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Taux de changes Fixing ECB', max_digits=8, null=True, verbose_name='Taux de convertion'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='montant_lc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='Montant Local'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(help_text='F.CFA pour le région CEMAC', on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Local'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='cpty',
            field=models.CharField(default='N/A', help_text="Bénéficiaire pour TRF/Donneur d'ordre pour RPT ", max_length=100, verbose_name='Contrepartie'),
            preserve_default=False,
        ),
    ]
