# Generated by Django 2.1.5 on 2019-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0071_auto_20190827_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ref_di',
            field=models.CharField(help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=50, unique=True, verbose_name='Réf décl'),
        ),
    ]
