# Generated by Django 2.1.5 on 2019-09-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0038_auto_20190903_1706'),
        ('transfert', '0073_auto_20190903_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomDossierMulti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom_pct', models.DecimalField(decimal_places=2, default=1, help_text='Pourcentage de domiciliation', max_digits=5, verbose_name='DOM Percentage')),
                ('obs', models.TextField(blank=True, default='Mettez vos observations:', max_length=1000, null=True)),
                ('date_verify', models.DateField(blank=True, editable=False, null=True, verbose_name='Date de Domiciliation')),
                ('date_val', models.DateField(blank=True, editable=False, null=True, verbose_name='Date de Réglement')),
                ('created', models.DateTimeField(editable=False)),
                ('chk_apure', models.BooleanField(default=False, help_text="Validation d'apurement", verbose_name='Chk Apure')),
                ('date_ap', models.DateField(blank=True, help_text="Date limite pour l'apurement", null=True, verbose_name='Date Limite')),
                ('time_ap', models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True)),
            ],
            options={
                'verbose_name': 'DOM Dossier Apurement',
                'verbose_name_plural': 'DOM Dossier Apurement',
                'db_table': 'dom_dossier_multi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomDossierApureProxy',
            fields=[
            ],
            options={
                'verbose_name': 'DOM Dossier BO Manager',
                'verbose_name_plural': 'DOM Dossier BO Manager',
                'proxy': True,
                'indexes': [],
            },
            bases=('transfert.domdossierctrl',),
        ),
        migrations.AlterModelOptions(
            name='domdossierctrl',
            options={'managed': True, 'verbose_name': 'DOM Dossier FO Manager', 'verbose_name_plural': 'DOM Dossier FO Manager'},
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossierctrl_ccy', to='util.Ccy', verbose_name='Ccy Devise'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Locale'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant devise de la déclaration', max_digits=18, verbose_name='Montant FX'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='montant_lc',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='Montant Local'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='Cochez si dossier est emis à la BEAC', verbose_name='EMIS'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ref_swift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Réf. Swift MT202'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_ccy', to='util.Ccy', verbose_name='Ccy Devise'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='ccy_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_ccy_lc', to='util.Ccy', verbose_name='Ccy Locale'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_exec',
            field=models.BooleanField(default=False, help_text="Check saisie d'Exécution", verbose_name='Exécution'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_fx',
            field=models.BooleanField(default=False, help_text="Cochez si il s'agit d'un taux FX spécial", verbose_name='FX Ticket'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Check paiement du Correspondant', verbose_name='Corresp'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='date_val',
            field=models.DateField(blank=True, help_text="Value date d'Exécution", null=True, verbose_name='Value Date'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='dossier_couvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierCouvr', to='transfert.TrfDossierCouvr', verbose_name='Couverture BEAC'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant devise de la déclaration', max_digits=18, verbose_name='Montant FX'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='montant_lc',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='Montant Local'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_input',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='ref_swift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence du paiement (Sygma/Swift etc.)'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='type_product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_type_product', to='util.CatalogTypeProduct', verbose_name='Type de produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='dossier_dom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossiermulti_dossier_dom', to='transfert.DomDossierCtrl', verbose_name='Dossier de Domiciliation'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='dossier_trf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossiermulti_dossier_trf', to='transfert.TrfDossierCtrl', verbose_name='Dossier de TRF/RPT'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='oper_ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_oper_ap', to=settings.AUTH_USER_MODEL, verbose_name='Agent de Validation'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_statut', to='util.Statut'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='dossier_dom_m2m',
            field=models.ManyToManyField(related_name='transfert_trfdossierctrl_dossier_dom_m2m', through='transfert.DomDossierMulti', to='transfert.DomDossierCtrl', verbose_name='Dossier de Domiciliation M2M'),
        ),
    ]
