# Generated by Django 2.1.5 on 2019-09-03 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0074_auto_20190903_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domdossierctrl',
            old_name='nature',
            new_name='nomenc_lv0',
        ),
        migrations.RemoveField(
            model_name='domdossierctrl',
            name='chk_ap',
        ),
        migrations.RemoveField(
            model_name='domdossierctrl',
            name='chk_pay',
        ),
        migrations.RemoveField(
            model_name='domdossierctrl',
            name='date_pay',
        ),
        migrations.RemoveField(
            model_name='domdossierctrl',
            name='no_inv',
        ),
        migrations.RemoveField(
            model_name='domdossiermulti',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='chk_dossier',
        ),
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='date_recu',
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='chk_apure',
            field=models.BooleanField(default=False, help_text="Validation d'apurement", verbose_name='Chk Apure'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='oper_ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_oper_ap', to=settings.AUTH_USER_MODEL, verbose_name='Agent de Validation'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='time_ap',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='ref_sygma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Réf. Sygma MT202'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='dossier_rtroc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierRtroc', to='transfert.TrfDossierCouvr', verbose_name='Retrocession BEAC'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='ref_exec',
            field=models.CharField(blank=True, help_text='ex: TRF/RPTXXXXXXX', max_length=50, null=True, verbose_name='Réf. Exécution'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ref_di',
            field=models.CharField(help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=15, unique=True, verbose_name='Réf décl'),
        ),
    ]
