# Generated by Django 2.1.5 on 2019-09-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0077_domdossiermulti_oper_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domdossiermulti',
            options={'managed': True, 'verbose_name': 'DOM Dossier Apurement', 'verbose_name_plural': 'TRF/RPT Dossier Apurement'},
        ),
    ]
