# Generated by Django 2.1.5 on 2019-09-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0079_auto_20190904_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='msg_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_msg_payment', to='settlement.SygmaCtrl', verbose_name='Payment Message'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_tproduct', to='util.CatalogTypeProduct', verbose_name='Type de produit'),
        ),
    ]
