# Generated by Django 2.1.5 on 2019-09-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0080_auto_20190904_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_type_product', to='util.CatalogTypeProduct', verbose_name='Type de produit'),
        ),
    ]
