# Generated by Django 2.1.5 on 2019-09-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0081_auto_20190904_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='nomenc_lv0',
            field=models.ForeignKey(default=23, limit_choices_to={'level': 0}, on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeCommercial'),
            preserve_default=False,
        ),
    ]
