# Generated by Django 2.1.5 on 2019-09-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0035_auto_20190826_1159'),
        ('transfert', '0082_auto_20190904_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
    ]
