# Generated by Django 2.1.5 on 2019-09-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0083_trfdossiercouvr_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domdossiermulti',
            unique_together={('dossier_dom', 'dossier_trf')},
        ),
    ]
