# Generated by Django 2.1.5 on 2019-09-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0085_trfdossierctrl_ctrl_cf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossierctrl',
            options={'managed': True, 'verbose_name': 'TRF/RPT/VIR Global Report', 'verbose_name_plural': 'TRF/RPT/VIR Global Report'},
        ),
    ]
