# Generated by Django 2.1.5 on 2019-09-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0086_auto_20190910_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossierctrl',
            options={'managed': True, 'verbose_name': 'TRF/RPT/VIR/CREDOC Reporting', 'verbose_name_plural': 'TRF/RPT/VIR/CREDOC Reporting'},
        ),
    ]
