# Generated by Django 2.1.5 on 2019-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0087_auto_20190910_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='chk_acc',
            field=models.BooleanField(default=False, help_text="Check d'Accord BEAC", verbose_name='PAY'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='date_acc',
            field=models.DateField(blank=True, help_text="Date d'Accord BEAC", null=True, verbose_name='Date Pay'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='ref_acc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Msg d'Accord BEAC"),
        ),
    ]
