# Generated by Django 2.1.5 on 2019-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0088_auto_20190912_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_acc',
            field=models.BooleanField(default=False, help_text="Check d'Accord BEAC", verbose_name='ACCEPT'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_acc',
            field=models.DateField(blank=True, help_text="Date d'Accord BEAC", null=True, verbose_name="Date d'Accept"),
        ),
    ]
