# Generated by Django 2.1.5 on 2019-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0089_auto_20190912_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_acc',
            field=models.BooleanField(default=False, help_text="Check d'Accept BEAC", verbose_name='ACCEPT'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_acc',
            field=models.DateField(blank=True, help_text="Date d'Accept BEAC", null=True, verbose_name="Date d'Accept"),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ref_acc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Msg d'Accept BEAC"),
        ),
    ]
