# Generated by Django 2.1.5 on 2019-09-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0090_auto_20190912_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_acc',
            field=models.BooleanField(default=False, help_text="Check d'Accept/Rejet BEAC", verbose_name='REP'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='Cochez si dossier est emis à la BEAC', verbose_name='EMI'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='date_acc',
            field=models.DateField(blank=True, help_text="Date d'Accept/Rejet BEAC", null=True, verbose_name='Date de Réponse'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ref_acc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Msg d'Accept/Rejet BEAC"),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='dossier_couvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierCouvr', to='transfert.TrfDossierCouvr', verbose_name='Couvr BEAC'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='dossier_rtroc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dossierRtroc', to='transfert.TrfDossierCouvr', verbose_name='Rtroc BEAC'),
        ),
    ]
