# Generated by Django 2.1.5 on 2019-09-12 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0091_auto_20190912_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
