# Generated by Django 2.2.6 on 2019-11-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0092_trfdossierctrl_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomDossierApureProxy',
        ),
        migrations.CreateModel(
            name='DomDossierInputProxy',
            fields=[
            ],
            options={
                'verbose_name': 'DOM Dossier Input',
                'verbose_name_plural': 'DOM Dossier Input',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transfert.domdossierctrl',),
        ),
        migrations.AlterModelOptions(
            name='domdossiermulti',
            options={'managed': True, 'verbose_name': 'DOM Dossier Apurement', 'verbose_name_plural': 'DOM Dossier Apurement'},
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='batch_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Batch NO.'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='chk_email',
            field=models.BooleanField(default=False, verbose_name='Chk Sent Email'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='sending_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_sending_oper', to=settings.AUTH_USER_MODEL, verbose_name='Sending user'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='template_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Template'),
        ),
        migrations.AlterField(
            model_name='domdossiermulti',
            name='dom_pct',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ratio de domiciliation', max_digits=5, verbose_name='DOM Ratio'),
        ),
        migrations.AlterField(
            model_name='domdossiermulti',
            name='dossier_dom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossiermulti_DomDossierMulti', to='transfert.DomDossierCtrl', verbose_name='Dossier de Domiciliation'),
        ),
        migrations.AlterField(
            model_name='domdossiermulti',
            name='dossier_trf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_domdossiermulti_DomDossierMulti', to='transfert.TrfDossierCtrl', verbose_name='Dossier de Paiement'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ref_swift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Réf. Swift MT950'),
        ),
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='ref_sygma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Réf. Sygma MT950/MT940'),
        ),
        migrations.AlterUniqueTogether(
            name='domdossierctrl',
            unique_together=set(),
        ),
    ]
