# Generated by Django 2.2.6 on 2019-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0093_auto_20191101_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomDossierInputProxy',
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant devise du paiement', max_digits=18, verbose_name='Montant Devise'),
        ),
    ]
