# Generated by Django 2.2.6 on 2019-11-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0094_auto_20191106_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossiermulti',
            name='ref_dom',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Réf Domiciliation'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='ref_trf',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Réf Transfert'),
        ),
    ]
