# Generated by Django 2.2.6 on 2019-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0095_auto_20191114_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domdossiermulti',
            name='ref_dom',
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='ref_di',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='REF_DI'),
        ),
        migrations.AlterField(
            model_name='domdossiermulti',
            name='ref_trf',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='REF_TRF'),
        ),
    ]
