# Generated by Django 2.2.6 on 2019-11-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0096_auto_20191114_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossiermulti',
            name='ref_di',
            field=models.CharField(blank=True, help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=15, null=True, verbose_name='REF_DI'),
        ),
    ]
