# Generated by Django 2.2.6 on 2019-11-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0097_auto_20191114_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossiermulti',
            name='ref_di',
            field=models.CharField(blank=True, help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=50, null=True, verbose_name='REF_DI'),
        ),
    ]
