# Generated by Django 2.2.6 on 2019-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0098_auto_20191114_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossierctrl',
            name='ref_di',
            field=models.CharField(help_text='Réf de déclaration distribuée par MINFI/GUOT ou Banque Centrale', max_length=50, unique=True, verbose_name='Réf décl'),
        ),
    ]
