# Generated by Django 2.2.6 on 2019-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0099_auto_20191114_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domdossiermulti',
            name='ref_trf',
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='ref_swift',
            field=models.CharField(blank=True, help_text='Référence du paiement (Sygma/Swift etc.)', max_length=50, null=True, verbose_name='REF_EXEC'),
        ),
    ]
