# Generated by Django 2.2.6 on 2019-11-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0100_auto_20191114_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domdossiermulti',
            name='ref_swift',
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='ref_exec',
            field=models.CharField(blank=True, help_text="Réf d'Exécution", max_length=50, null=True, verbose_name='REF_EXEC'),
        ),
    ]
