# Generated by Django 2.2.6 on 2019-11-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0038_auto_20190903_1706'),
        ('transfert', '0101_auto_20191114_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossiermulti',
            name='nomenc_lv0',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_nomenc_lv0', to='util.CatalogTypeCommercial'),
        ),
    ]
