# Generated by Django 2.2.6 on 2019-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0102_domdossiermulti_nomenc_lv0'),
    ]

    operations = [
        migrations.AddField(
            model_name='domdossiermulti',
            name='dom_pct_montant_lc',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='dom_pct_montant_lc'),
        ),
    ]
