# Generated by Django 2.2.6 on 2019-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0103_domdossiermulti_dom_pct_montant_lc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossiermulti',
            name='dom_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Ratio de domiciliation', max_digits=5, null=True, verbose_name='DOM Ratio'),
        ),
    ]
