# Generated by Django 2.2.6 on 2019-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0104_auto_20191205_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domdossiermulti',
            name='dom_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, help_text='Ratio de domiciliation', max_digits=7, null=True, verbose_name='DOM Ratio'),
        ),
    ]
