# Generated by Django 2.2.6 on 2020-01-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200114_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0105_auto_20191205_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trfdossierctrl',
            options={'managed': True, 'verbose_name': 'TRF/RPT/VIR/CREDOC Reception', 'verbose_name_plural': 'TRF/RPT/VIR/CREDOC Reception'},
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='batch_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Batch NO.'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='chk_notify',
            field=models.BooleanField(default=False, help_text='Check Notification', verbose_name='NTFY'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Check Reception', verbose_name='Recv'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_message', to='notification.EmailCtrl'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='oper_recv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossierctrl_recv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='template_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='domdossierctrl',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='chk_notify',
            field=models.BooleanField(default=False, help_text='Check Notification', verbose_name='NTFY'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Check Reception', verbose_name='Recv'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_message', to='notification.EmailCtrl'),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='oper_recv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_domdossiermulti_recv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domdossiermulti',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='batch_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Batch NO.'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='chk_notify',
            field=models.BooleanField(default=False, help_text='Check Notification', verbose_name='NTFY'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Check Reception', verbose_name='Recv'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_message', to='notification.EmailCtrl'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='oper_recv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossiercouvr_recv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='template_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='trfdossiercouvr',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='batch_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Batch NO.'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_notify',
            field=models.BooleanField(default=False, help_text='Check Notification', verbose_name='NTFY'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_recu',
            field=models.BooleanField(default=False, help_text="Check saisie d'Exécution", verbose_name='Exéc'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Check Reception', verbose_name='Recv'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_message', to='notification.EmailCtrl'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='oper_recv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_recv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='template_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='type_fund',
            field=models.IntegerField(blank=True, choices=[(1, '\\COUVR'), (2, '\\ENVLP'), (3, '\\FPROP')], help_text='Source de fond à utiliser', null=True, verbose_name='TFund'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='domdossierctrl',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_ccy', to='util.Ccy', verbose_name='Ccy'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_exec',
            field=models.BooleanField(default=False, help_text="Check saisie d'Exécution", verbose_name='Exéc'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_pay',
            field=models.BooleanField(default=False, help_text='Check paiement du Correspondant', verbose_name='Cosp'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='cpty',
            field=models.CharField(help_text="Bénéficiaire pour TRF/Donneur d'ordre pour RPT", max_length=100, verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='created',
            field=models.DateTimeField(editable=False, help_text='Heure de Saisie', verbose_name='Time Input'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant devise du paiement', max_digits=18, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='oper_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_trfdossierctrl_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Oper Input'),
        ),
    ]
