# Generated by Django 2.2.6 on 2020-02-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfert', '0111_auto_20200204_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='chk_dcc',
            field=models.BooleanField(default=False, help_text='Check LAB-FT', verbose_name='Chk DCC'),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='obs_dcc',
            field=models.TextField(blank=True, default='', help_text='Observation DCC', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='oper_dcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_trfdossierctrl_dcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfdossierctrl',
            name='time_dcc',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Chk DCC', null=True),
        ),
    ]
