# Generated by Django 2.2.6 on 2020-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0112_auto_20200213_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_dcc',
            field=models.BooleanField(blank=True, default=False, help_text='Check LAB-FT', null=True, verbose_name='Chk DCC'),
        ),
    ]
