# Generated by Django 2.2.6 on 2020-02-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0114_trfdossierctrl_type_dcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfdossierctrl',
            name='type_dcc',
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_dcc',
            field=models.BooleanField(blank=True, help_text='Check LAB-FT', null=True, verbose_name='Chk DCC'),
        ),
    ]
