# Generated by Django 2.2.6 on 2020-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0115_auto_20200213_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_dcc',
            field=models.BooleanField(blank=True, choices=[(None, '\\ATTN'), (0, '\\REJET'), (1, '\\ACK')], help_text='Check LAB-FT', null=True, verbose_name='Chk DCC'),
        ),
    ]
