# Generated by Django 2.2.6 on 2020-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0117_auto_20200213_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfdossierctrl',
            name='type_dcc',
            field=models.IntegerField(blank=True, choices=[(None, '\\ATTN'), (0, '\\REJET'), (1, '\\ACK')], help_text="Avis de DCC sur l'EXAMEN LAB-FT", null=True, verbose_name='Type DCC'),
        ),
        migrations.AlterField(
            model_name='trfdossierctrl',
            name='chk_dcc',
            field=models.BooleanField(default=False, help_text='Check LAB-FT', verbose_name='Chk DCC'),
        ),
    ]
