# Generated by Django 2.2.6 on 2020-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0118_auto_20200213_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfdossiercouvr',
            name='montant_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du flux Sortant', max_digits=18, null=True, verbose_name='Montant Sortant'),
        ),
    ]
