# Generated by Django 2.2.6 on 2019-11-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0038_auto_20190903_1706'),
        ('tiers', '0037_auto_20190913_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_verify', models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify')),
                ('time_verify', models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True)),
                ('chk_approv', models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv')),
                ('time_approv', models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True)),
                ('obs', models.TextField(blank=True, max_length=1000, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_email', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('template_key', models.CharField(max_length=255, unique=True)),
                ('template_type', models.IntegerField(choices=[(1, 'Text Template'), (2, 'Html Template'), (3, 'Ext. Template')], default=1)),
                ('int_template', models.TextField(blank=True, null=True)),
                ('ext_template', models.FileField(blank=True, null=True, upload_to=notification.models.upload_path_handler)),
                ('type_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('type_action', models.CharField(blank=True, max_length=255, null=True)),
                ('oper_approv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailtemplate_approv', to=settings.AUTH_USER_MODEL)),
                ('oper_verify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailtemplate_verify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template Mgr.',
                'verbose_name_plural': 'Email Template Mgr.',
                'db_table': 'email_template',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_verify', models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify')),
                ('time_verify', models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True)),
                ('chk_approv', models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv')),
                ('time_approv', models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True)),
                ('obs', models.TextField(blank=True, max_length=1000, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_email', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('batch_no', models.CharField(blank=True, max_length=19, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Tapez le code client ici', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('oper_approv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailctrl_approv', to=settings.AUTH_USER_MODEL)),
                ('oper_verify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailctrl_verify', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailctrl_statut', to='util.Statut')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_emailctrl_template', to='notification.EmailTemplate', verbose_name='Email Template')),
            ],
            options={
                'verbose_name': 'Email Ctrl.',
                'verbose_name_plural': 'Email Ctrl.',
                'db_table': 'email_ctrl',
                'managed': True,
            },
        ),
    ]
