# Generated by Django 2.2.6 on 2019-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailctrl',
            name='subject_type',
            field=models.IntegerField(choices=[(1, 'Text Subject'), (2, 'Html Subject')], default=1),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_type',
            field=models.IntegerField(choices=[(1, 'Text Subject'), (2, 'Html Subject')], default=1),
        ),
    ]
