# Generated by Django 2.2.6 on 2019-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191119_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailctrl',
            name='subject_type',
        ),
    ]
