# Generated by Django 2.2.6 on 2019-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_emailctrl_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailctrl',
            name='subject',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
