# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20171026_0911'),
        ('interface', '0002_remove_apbkcom_ctrl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApBkcom',
        ),
    ]
