# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_delete_apbkcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApBkcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, db_column='AGE', max_length=5, null=True)),
                ('date_val', models.DateField(db_column='DATE_VAL')),
                ('date_cr', models.DateField(blank=True, db_column='DATE_CR', null=True)),
                ('date_dr', models.DateField(blank=True, db_column='DATE_DR', null=True)),
                ('code_client', models.CharField(blank=True, db_column='CLI', max_length=6, null=True)),
                ('acc', models.CharField(db_column='ACC', max_length=6)),
                ('acc_txt', models.CharField(blank=True, db_column='ACC_TXT', max_length=100, null=True)),
                ('ccy_code', models.CharField(db_column='CCY_CODE', max_length=3)),
                ('montant', models.DecimalField(db_column='AMT', decimal_places=2, max_digits=18)),
                ('timestamp', models.CharField(db_column='TIMESTAMP', max_length=12)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Interface Amplitude A/C Balance (BKCOM)',
                'db_table': 'AP_BKCOM',
                'verbose_name': 'Interface Amplitude A/C Balance (BKCOM)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apbkcom',
            unique_together=set([('date_val', 'code_client', 'entity', 'acc', 'ccy_code')]),
        ),
    ]
