# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20171026_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apbkcom',
            name='date_cr',
        ),
        migrations.RemoveField(
            model_name='apbkcom',
            name='date_dr',
        ),
    ]
