# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20171026_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='apbkcom',
            name='date_cr',
            field=models.DateField(blank=True, db_column='DATE_CR', null=True),
        ),
        migrations.AddField(
            model_name='apbkcom',
            name='date_dr',
            field=models.DateField(blank=True, db_column='DATE_DR', null=True),
        ),
        migrations.AlterField(
            model_name='apbkcom',
            name='date_val',
            field=models.DateField(blank=True, db_column='DATE_VAL', null=True),
        ),
    ]
