# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20171102_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rpt', models.DateField(db_column='DRT')),
                ('date_cpt', models.DateField(db_column='DCO')),
                ('date_val', models.DateField(db_column='DVA')),
                ('cha_lv2', models.CharField(db_column='CHA2', max_length=200)),
                ('cha_lv3', models.CharField(db_column='CHA3', max_length=200)),
                ('code_client', models.CharField(blank=True, db_column='CLI', max_length=6, null=True)),
                ('ccy_code', models.CharField(db_column='DEV', max_length=3)),
                ('acc', models.CharField(db_column='NCP', max_length=11)),
                ('solde_t0', models.DecimalField(db_column='SHI', decimal_places=2, max_digits=18)),
                ('mvmt_dr', models.DecimalField(db_column='MVTD', decimal_places=2, max_digits=18)),
                ('mvmt_cr', models.DecimalField(db_column='MVTC', decimal_places=2, max_digits=18)),
                ('solde_t1', models.DecimalField(db_column='SDE', decimal_places=2, max_digits=18)),
                ('ctrl', models.DecimalField(db_column='CTRL', decimal_places=2, max_digits=18)),
                ('timestamp', models.CharField(db_column='TIMESTAMP', max_length=12)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Interface Amplitude Trial Balance',
                'db_table': 'AP_TB',
                'verbose_name': 'Interface Amplitude Trial Balance',
            },
        ),
        migrations.AlterUniqueTogether(
            name='aptb',
            unique_together=set([('date_rpt', 'acc', 'ccy_code')]),
        ),
    ]
