# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20180321_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptb',
            options={'managed': True, 'verbose_name': 'Interface Amplitude Trial Balance (TB)', 'verbose_name_plural': 'Interface Amplitude Trial Balance (TB)'},
        ),
    ]
