# Generated by Django 2.1.2 on 2019-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20180322_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apbkcli',
            name='ref_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
