# Generated by Django 2.1.5 on 2019-03-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20190330_2259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apbkcli',
            table='ap_bkcli',
        ),
        migrations.AlterModelTable(
            name='apbkcom',
            table='ap_bkcom',
        ),
        migrations.AlterModelTable(
            name='apbkdopi',
            table='ap_bkdopi',
        ),
        migrations.AlterModelTable(
            name='apbkmvt',
            table='ap_bkmvt',
        ),
        migrations.AlterModelTable(
            name='aptb',
            table='ap_tb',
        ),
    ]
