# Generated by Django 2.1.5 on 2019-03-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20190331_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sygma',
            table='sygma',
        ),
    ]
