# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cashflow', '0001_initial'),
        ('settlement', '0002_auto_20171008_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowdetail',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.AccountCorresp'),
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='corresp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.Corresp'),
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.TreasuryPosition'),
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='sygmaCtrl',
            field=models.ManyToManyField(blank=True, to='settlement.SygmaCtrl'),
        ),
        migrations.CreateModel(
            name='CashFlowDetailSingleFlowProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cashflow.cashflowdetail',),
        ),
        migrations.CreateModel(
            name='CashFlowDetailTwoWayFlowProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cashflow.cashflowdetailsingleflowproxy',),
        ),
        migrations.CreateModel(
            name='CashFlowDetailTwoWayFxProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cashflow.cashflowdetailsingleflowproxy',),
        ),
    ]
