# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_auto_20171008_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowdetail',
            options={'managed': True, 'ordering': ('-date_val', 'content_type', 'object_id')},
        ),
        migrations.AlterField(
            model_name='cashflowdetail',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.AccountCorresp'),
        ),
        migrations.AlterField(
            model_name='cashflowdetail',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.TreasuryPosition'),
        ),
    ]
