# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_cashflowfile_chk_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowfile',
            name='chk_actif',
        ),
    ]
