# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_remove_cashflowfile_chk_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowfile',
            name='chk_actif',
            field=models.BooleanField(default=False, help_text='Check if actif', verbose_name='Chk Actif'),
        ),
        migrations.AlterModelTable(
            name='cashflowfile',
            table='TRESOR_CASHFLOW_FILE',
        ),
    ]
