# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util.fileStorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0008_catalog_type_product'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0009_auto_20171009_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=util.fileStorage.models.upload_path_handler)),
                ('chk_actif', models.BooleanField(default=False, help_text='Check if actif', verbose_name='Chk Actif')),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Doc')),
                ('oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CASHFLOW_FILE',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='cashflowdetail',
            table='CASHFLOW_DETAIL',
        ),
    ]
