# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_auto_20171008_1015'),
        ('cashflow', '0010_auto_20171009_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowdetail',
            name='sygmaCtrl',
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='sygmaCtrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.SygmaCtrl'),
        ),
    ]
