# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_cashflowdetail_type_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlowDetailTwoWayFlowProxy',
        ),
    ]
