# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_delete_cashflowdetailtwowayflowproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowdetail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.AccountCorresp'),
        ),
    ]
