# Generated by Django 2.1.5 on 2019-03-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_auto_20180509_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowfile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cashflowfile',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='cashflowfile',
            name='oper',
        ),
        migrations.DeleteModel(
            name='CashFlowFile',
        ),
    ]
