# Generated by Django 2.1.2 on 2019-03-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_auto_20190318_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlowDetailTwoWayFxProxy',
        ),
        migrations.AlterField(
            model_name='cashflowdetail',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_cashflowdetail_type_product', to='util.CatalogTypeProduct'),
        ),
    ]
