# Generated by Django 2.1.2 on 2019-03-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0016_auto_20190330_0445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlowDetailSingleFlowProxy',
        ),
    ]
