# Generated by Django 2.1.5 on 2019-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0017_delete_cashflowdetailsingleflowproxy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashflowdetail',
            table='cashflow_detail',
        ),
    ]
