# Generated by Django 2.1.5 on 2019-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_auto_20190331_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowdetail',
            name='releveCmpt',
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='ref_swift',
            field=models.CharField(blank=True, help_text='Référence swift sur MT950', max_length=50, null=True, verbose_name='Réf. Swift'),
        ),
    ]
