# Generated by Django 2.1.5 on 2019-08-26 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0015_auto_20190812_1158'),
        ('cashflow', '0019_auto_20190826_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowdetail',
            name='ref_swift',
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='releveCmpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.TreasuryPosition'),
        ),
    ]
