# Generated by Django 2.1.5 on 2019-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0020_auto_20190826_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowdetail',
            name='releveCmpt',
        ),
        migrations.AddField(
            model_name='cashflowdetail',
            name='ref_swift',
            field=models.CharField(blank=True, help_text='Référence swift sur MT950', max_length=50, null=True, verbose_name='Réf. Swift'),
        ),
    ]
