# -*- coding: utf-8 -*-
"""
Django settings for treasury-admin project.

Generated by 'django-admin startproject' using Django

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import base64

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1qc$rdy#sed!6bran5xi++$q+ui4kpr^bdzx)t-uae0!!hn%0u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['10.205.176.250','localhost'] #'10.208.41.250',


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    #view-connection
    'dal',
    'dal_select2',
    #standards
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #
    #'debug_toolbar',
    #'django_extensions', #used for embedded foreignkey fields
    'import_export', 
    #
    'notification',
    'interface',
    'util',
    'tiers.apps.TiersConfig',
    'treasury.apps.TreasuryConfig',
    'transfert.apps.TransfertConfig',
    'cashflow.apps.CashFlowConfig',    
    'settlement',      
    'bureau',
    'accounting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'treasury-admin.urls'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static")
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"media")
#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+"/frontend/dist", BASE_DIR+"/templates"],        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                ],
            },
        },
]

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]

## Database
## https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'proddb',
    'HOST': '10.108.1.10',
    'PORT': '3306',
    'USER': 'proddba',
    'PASSWORD': 'dba@BSCA123', 
    #this avoids foreign key check in migrations
    "init_command": "SET foreign_key_checks = 0;",        
    },  
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
]

WSGI_APPLICATION = 'treasury-admin.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

#LANGUAGE_CODE = 'zh-hans'
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ' '
NUMBER_GROUPING = 3

DATE_INPUT_FORMATS = '%Y-%m-%d'



# Additional locations of static files  
STATICFILES_DIRS = [   
    os.path.join(BASE_DIR,"static"),
    BASE_DIR+"/frontend/dist/static",
    #'/var/www/static'
]

IMPORT_EXPORT_USE_TRANSACTIONS = True

#for disable '//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
JQUERY_URL = True

CORS_ORIGIN_ALLOW_ALL = True

TEMPLATE_DEBUG = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000