# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('settlement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryposition',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.AccountCorresp'),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='corresp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.Corresp'),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='uti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sygmactrl',
            name='clientCtrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl'),
        ),
        migrations.AlterUniqueTogether(
            name='treasuryposition',
            unique_together=set([('date_val', 'corresp', 'account')]),
        ),
    ]
