# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('settlement', '0002_auto_20171008_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryposition',
            name='type_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
    ]
