# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_auto_20180326_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryposition',
            name='nature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
