# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_auto_20180326_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryposition',
            name='type_tiers',
            field=models.CharField(max_length=50),
        ),
    ]
