# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_auto_20180326_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryposition',
            name='type_tiers',
        ),
    ]
