# Generated by Django 2.1.5 on 2019-03-18 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import settlement.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0007_remove_treasuryposition_type_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryposition',
            name='bs_file',
            field=models.FileField(blank=True, help_text='Télécharger le relevé de compte scanné en PDF', null=True, upload_to=settlement.models.upload_path_handler, verbose_name='Rélevé de compte'),
        ),
        migrations.AlterField(
            model_name='treasuryposition',
            name='uti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
