# Generated by Django 2.1.2 on 2019-03-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0020_auto_20190330_0404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlement', '0008_auto_20190318_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryposition',
            name='bs_file',
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_treasuryposition_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_treasuryposition_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='treasuryposition',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='treasuryposition',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde de Clôture', max_digits=18, verbose_name='Closing Balance'),
        ),
        migrations.AlterField(
            model_name='treasuryposition',
            name='montant_op',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Solde d'Ouverture", max_digits=18, null=True, verbose_name='Opening Balance'),
        ),
        migrations.AlterField(
            model_name='treasuryposition',
            name='uti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_treasuryposition_oper', to=settings.AUTH_USER_MODEL, verbose_name='Oper Input'),
        ),
    ]
