# Generated by Django 2.1.2 on 2019-03-30 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlement', '0009_auto_20190330_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryposition',
            name='oper_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_treasuryposition_oper_input', to=settings.AUTH_USER_MODEL, verbose_name='Oper Input'),
        ),
    ]
