# Generated by Django 2.1.2 on 2019-03-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0010_treasuryposition_oper_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryposition',
            name='uti',
        ),
    ]
