# Generated by Django 2.1.5 on 2019-03-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0011_remove_treasuryposition_uti'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sygmactrl',
            table='tresor_sygma_ctrl',
        ),
    ]
