# Generated by Django 2.1.5 on 2019-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0012_auto_20190331_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treasuryposition',
            table='tresor_loro_corresp',
        ),
    ]
