# Generated by Django 2.1.5 on 2019-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0013_auto_20190331_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryposition',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
