# Generated by Django 2.1.5 on 2019-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0014_auto_20190403_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryposition',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv'),
        ),
        migrations.AlterField(
            model_name='treasuryposition',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify'),
        ),
    ]
