# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import treasury.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('util', '0008_catalog_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(0, 'Titre CT'), (1, 'Titre LT')], default=0)),
                ('ref_id', models.CharField(max_length=50)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_val', models.DateField()),
                ('date_end', models.DateField()),
                ('daycount', models.CharField(max_length=12)),
                ('taux', models.DecimalField(decimal_places=10, max_digits=14)),
                ('repayment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('chk_end', models.BooleanField(default=False, help_text='Check if security has been fully repaid', verbose_name='Chk End')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.AccountCorresp')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Broker')),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
                ('corresp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Corresp')),
                ('depository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Depository')),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Emetteur')),
            ],
            options={
                'ordering': ('-date_val',),
                'verbose_name': 'FI Manager',
                'db_table': 'TRESOR_FI_MGR',
                'managed': True,
                'verbose_name_plural': 'FI Manager',
            },
        ),
        migrations.CreateModel(
            name='FIFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.FI')),
            ],
            options={
                'db_table': 'TRESOR_FI_MGR_FILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(0, 'Nivellement'), (1, 'FxCash'), (2, 'FxSpot'), (3, 'FxFwd')], default=0)),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_trd', models.DateField(verbose_name='Trading Date')),
                ('date_val', models.DateField(verbose_name='Value Date')),
                ('fx_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('montant_in', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Receving Value')),
                ('montant_out', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Payment Value')),
                ('chk_end', models.BooleanField(default=False, help_text='Check if fully settled', verbose_name='Chk End')),
                ('account_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_account_in', to='tiers.AccountCorresp', verbose_name='Receving a/c')),
                ('account_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_account_out', to='tiers.AccountCorresp', verbose_name='Payment a/c')),
                ('ccy_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy')),
                ('ccy_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_ccy_out', to='util.Ccy', verbose_name='Payment Ccy')),
                ('ccy_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.CcyPair')),
                ('corresp_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_corresp_in', to='tiers.Corresp', verbose_name='Receving Bank')),
                ('corresp_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_corresp_out', to='tiers.Corresp', verbose_name='Payment Bank')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Cpty')),
            ],
            options={
                'ordering': ('-date_val',),
                'verbose_name': 'FX Manager',
                'db_table': 'TRESOR_FX_MGR',
                'managed': True,
                'verbose_name_plural': 'FX Manager',
            },
        ),
        migrations.CreateModel(
            name='FXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.FX')),
            ],
            options={
                'db_table': 'TRESOR_FX_MGR_FILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(0, 'Emprunt IB'), (1, 'Pr\xeat IB'), (9, 'Cr\xe9dit Import')], default=0)),
                ('ref_id', models.CharField(max_length=50)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_val', models.DateField()),
                ('date_end', models.DateField()),
                ('daycount', models.CharField(max_length=12)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Taux d'int\xe9r\xeat en %")),
                ('taux_fx', models.FloatField(blank=True, default=1, null=True, verbose_name='Taux de change')),
                ('repayment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('chk_end', models.BooleanField(default=False, help_text='Check if fully repaid', verbose_name='Chk End')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.AccountCorresp')),
                ('ccy_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mm_ccy_in', to='util.Ccy', verbose_name='Trade Ccy')),
                ('ccy_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mm_ccy_out', to='util.Ccy', verbose_name='Repayment Ccy')),
                ('corresp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Corresp')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.Cpty')),
            ],
            options={
                'verbose_name': 'MM Manager',
                'db_table': 'TRESOR_MM_MGR',
                'managed': True,
                'verbose_name_plural': 'MM Manager',
            },
        ),
        migrations.CreateModel(
            name='MMFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.MM')),
            ],
            options={
                'db_table': 'TRESOR_MM_MGR_FILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TresorLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(blank=True, help_text='Date Valeur du dernier relev\xe9 de compte', null=True, verbose_name='Date du relev\xe9')),
                ('montant_val', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='La Solde du dernier relv\xe9 de compte', max_digits=18, null=True, verbose_name='Balance du correspondant')),
                ('montant_act', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='La Solde Actuel', max_digits=18, null=True, verbose_name='Montant Actuel (Estim\xe9)')),
                ('montant_min', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='La Solde Minimum', max_digits=18, null=True, verbose_name='Min Balance')),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='La Solde Maximum', max_digits=18, null=True, verbose_name='Max Balance')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.AccountCorresp')),
                ('corresp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.Corresp')),
            ],
            options={
                'db_table': 'TRESOR_LIMIT',
                'verbose_name': 'Contr\xf4le de la limite de tr\xe9sorerie',
                'verbose_name_plural': 'Contr\xf4le de la limite de tr\xe9sorerie',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='tresorlimit',
            unique_together=set([('account',)]),
        ),
    ]
