# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_auto_20180321_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='ctrl_cf',
            field=models.BooleanField(default=True, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow'),
        ),
    ]
