# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_fx_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fi',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='fi',
            name='depository',
        ),
        migrations.RemoveField(
            model_name='fi',
            name='emetteur',
        ),
        migrations.RemoveField(
            model_name='fi',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='mm',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='mm',
            name='nature',
        ),
        migrations.AlterField(
            model_name='fx',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl', verbose_name='Contrepartie/Client'),
        ),
    ]
