# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_auto_20180323_1234'),
        ('treasury', '0006_auto_20180323_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_cpty', to='tiers.ClientCtrl', verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_client', to='tiers.ClientCtrl', verbose_name='Contrepartie/Client'),
        ),
    ]
