# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_auto_20180323_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fx',
            name='cpty',
        ),
    ]
