# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0021_auto_20180324_1403'),
        ('treasury', '0011_auto_20180324_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='mm',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mm_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
    ]
