# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import treasury.models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('tiers', '0021_auto_20180324_1403'),
        ('treasury', '0012_mm_cpty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxCli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_cf', models.BooleanField(default=True, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_trd', models.DateField(verbose_name='Trading Date')),
                ('date_val', models.DateField(verbose_name='Value Date')),
                ('fx_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('montant_in', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Receving Value')),
                ('montant_out', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Paying Value')),
                ('chk_end', models.BooleanField(default=False, help_text='Check if fully settled', verbose_name='Chk End')),
                ('nature', models.IntegerField(choices=[(0, '/FX'), (1, '/FEE')], default=1)),
                ('fee_rate', models.FloatField(default=0, help_text='Taux de commission(ex. 2,0% = 0.02)', verbose_name='Fee Rate(HT)')),
                ('montant_tva', models.IntegerField(blank=True, null=True, verbose_name='TVA(XAF)')),
                ('chk_ok', models.BooleanField(default=False, help_text='Cochez si le taux fx a \xe9t\xe9 approuv\xe9', verbose_name='Chk OK')),
                ('date_end', models.DateField(blank=True, help_text='Date de Facturation', null=True, verbose_name='Pay Date')),
                ('ccy_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fxcli_fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy')),
                ('ccy_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fxcli_fx_ccy_out', to='util.Ccy', verbose_name='Paying Ccy')),
                ('ccy_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.CcyPair')),
            ],
            options={
                'verbose_name': 'FX CLI Manager',
                'db_table': 'TRF_DOSSIER_FX_CLI',
                'managed': True,
                'verbose_name_plural': 'FX CLI Manager',
            },
        ),
        migrations.CreateModel(
            name='FXCliFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TRESOR_FX_CLI_MGR_FILE',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='fx',
            name='client',
        ),
        migrations.AlterField(
            model_name='fx',
            name='account_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_account_out', to='tiers.AccountCorresp', verbose_name='Paying a/c'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fx_fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fx_fx_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='corresp_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_corresp_out', to='tiers.Corresp', verbose_name='Paying Bank'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_fx_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='montant_out',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Paying Value'),
        ),
        migrations.AddField(
            model_name='fxclifile',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.FX'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='cliFile',
            field=models.ForeignKey(blank=True, help_text='Client Confirmation', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury.FXCliFile', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_client', to='tiers.ClientCtrl', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_fx_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Product'),
        ),
    ]
