# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0017_auto_20180325_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcli',
            name='ctrl_cf',
            field=models.BooleanField(default=False, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='date_trd',
            field=models.DateField(blank=True, null=True, verbose_name='Trading Date'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='date_val',
            field=models.DateField(blank=True, null=True, verbose_name='Value Date'),
        ),
        migrations.AlterField(
            model_name='fxclifile',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.FXCli'),
        ),
    ]
