# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0019_auto_20180325_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxclifile',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='fxcli',
            name='cliFile',
        ),
        migrations.DeleteModel(
            name='FXCliFile',
        ),
    ]
