# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import treasury.models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0020_auto_20180325_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXCliFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.FXCli')),
            ],
            options={
                'db_table': 'TRESOR_FX_CLI_FILE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fxcli',
            name='fxCliFile',
            field=models.ForeignKey(blank=True, help_text='Client Confirmation', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury.FXCliFile', verbose_name='Document'),
        ),
    ]
