# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0011_auto_20180326_1157'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('treasury', '0023_auto_20180325_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcli',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='fxcli',
            unique_together=set([('type_product', 'content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='fxcli',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
