# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0024_auto_20180327_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fxcli_fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fxcli_fx_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='montant_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Receving Value'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='montant_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Paying Value'),
        ),
    ]
