# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0025_auto_20180327_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcli',
            name='cliFile',
            field=models.ForeignKey(blank=True, help_text='Client Confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_cliFile', to='tiers.ClientCtrlFile', verbose_name='Document'),
        ),
    ]
