# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0026_auto_20180413_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx',
            name='fx_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='fx_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
