# Generated by Django 2.1.5 on 2019-03-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0027_auto_20180415_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='type_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 39}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Product'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='account_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_ac_in', to='tiers.AccountCorresp', verbose_name='Receving a/c'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='account_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_ac_out', to='tiers.AccountCorresp', verbose_name='Paying a/c'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fx_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CcyPair'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='corresp_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_corresp_in', to='tiers.Corresp', verbose_name='Receving Bank'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='corresp_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_corresp_out', to='tiers.Corresp', verbose_name='Paying Bank'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='type_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 41}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Product'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CcyPair'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_client', to='tiers.ClientCtrl', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='ccy_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_mm_ccy_in', to='util.Ccy', verbose_name='Trade Ccy'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='ccy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_ccy_out', to='util.Ccy', verbose_name='Repayment Ccy'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_cpty', to='tiers.Cpty', verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='type_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 40}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Product'),
        ),
    ]
