# Generated by Django 2.1.2 on 2019-03-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0024_auto_20190330_0412'),
        ('util', '0020_auto_20190330_0404'),
        ('treasury', '0028_auto_20190318_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='fi',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='fi',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_client', to='tiers.ClientCtrl', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='fi',
            name='ctrl_cf',
            field=models.BooleanField(default=True, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow'),
        ),
        migrations.AddField(
            model_name='fi',
            name='date_trd',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Trading Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fi',
            name='depo',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_depo', to='tiers.Depo', verbose_name='Depository'),
        ),
        migrations.AddField(
            model_name='fi',
            name='emetteur',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_emetteur', to='tiers.ClientCtrl', verbose_name='Emetteur'),
        ),
        migrations.AddField(
            model_name='fi',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fi',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fi',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fi',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='fi',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='fx',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='fx',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_client', to='tiers.ClientCtrl', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='fx',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Settlement Date'),
        ),
        migrations.AddField(
            model_name='fx',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fx',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fx',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AddField(
            model_name='mm',
            name='ccy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_mm_ccy', to='util.Ccy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mm',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='mm',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='mm',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tapez le code client ici Amplitude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_client', to='tiers.ClientCtrl', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='mm',
            name='ctrl_cf',
            field=models.BooleanField(default=True, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow'),
        ),
        migrations.AddField(
            model_name='mm',
            name='date_trd',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Trading Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mm',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mm',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mm',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mm',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='mm',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AlterField(
            model_name='fi',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_ac', to='tiers.AccountCorresp', verbose_name='Correpondant A/C.'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_fi_ccy', to='util.Ccy'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='chk_end',
            field=models.BooleanField(default=False, help_text='Check if fully settled', verbose_name='Chk End'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='corresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_corresp', to='tiers.Corresp', verbose_name='Correpondant Bank'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='date_end',
            field=models.DateField(verbose_name='Maturity Date'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='date_val',
            field=models.DateField(verbose_name='Value Date'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_type_product', to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='ccy_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_ccy_pair', to='util.CcyPair', verbose_name='Currency Pair'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez code client ici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_cpty', to='tiers.Cpty', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='fx_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fx',
            name='montant_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Receving Value'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='montant_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Paying Value'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_type_product', to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ccy_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_ccy_pair', to='util.CcyPair', verbose_name='Currency Pair'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez code client ici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_cpty', to='tiers.Cpty', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='ctrl_cf',
            field=models.BooleanField(default=True, help_text='Check if genrerate cashflow', verbose_name='Genr Cashflow'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Settlement Date'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='date_trd',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Trading Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='date_val',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Value Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='fx_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='montant_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Receving Value'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='montant_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Paying Value'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_type_product', to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_ac', to='tiers.AccountCorresp', verbose_name='Correpondant A/C.'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='ccy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_ccy_in', to='util.Ccy', verbose_name='Receving Ccy'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='ccy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_ccy_out', to='util.Ccy', verbose_name='Paying Ccy'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='chk_end',
            field=models.BooleanField(default=False, help_text='Check if fully settled', verbose_name='Chk End'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='corresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_corresp', to='tiers.Corresp', verbose_name='Correpondant Bank'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='cpty',
            field=models.ForeignKey(blank=True, help_text='Tapez code client ici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_cpty', to='tiers.Cpty', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='date_end',
            field=models.DateField(verbose_name='Maturity Date'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='date_val',
            field=models.DateField(verbose_name='Value Date'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='taux',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='mm',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_type_product', to='util.CatalogTypeProduct'),
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_tresorlimit_account', to='tiers.AccountCorresp', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='corresp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_tresorlimit_corresp', to='tiers.Corresp', verbose_name='Corresp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='date_val',
            field=models.DateField(blank=True, help_text='MT950 Value Date', null=True, verbose_name='Date du relevé'),
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='montant_act',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde Previsonnelle', max_digits=18, verbose_name='Estimated Balance'),
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='montant_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solde Minimum', max_digits=18, null=True, verbose_name='Min Balance'),
        ),
        migrations.AlterField(
            model_name='tresorlimit',
            name='montant_val',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solde du dernier relvé de compte', max_digits=18, null=True, verbose_name='MT950 Balance'),
        ),
    ]
