# Generated by Django 2.1.2 on 2019-03-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0029_auto_20190330_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxcli',
            name='cliFile',
        ),
    ]
