# Generated by Django 2.1.2 on 2019-03-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0030_remove_fxcli_clifile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifile',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='fxfile',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='mmfile',
            name='dossier',
        ),
        migrations.AlterUniqueTogether(
            name='tresorlimit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tresorlimit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tresorlimit',
            name='corresp',
        ),
        migrations.DeleteModel(
            name='FIFile',
        ),
        migrations.DeleteModel(
            name='FXFile',
        ),
        migrations.DeleteModel(
            name='MMFile',
        ),
        migrations.DeleteModel(
            name='TresorLimit',
        ),
    ]
