# Generated by Django 2.1.5 on 2019-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0032_auto_20190331_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fxcli',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='fxcli',
            index_together=set(),
        ),
    ]
