# Generated by Django 2.1.5 on 2019-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0033_auto_20190401_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fx',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mm',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
