# Generated by Django 2.1.5 on 2019-06-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0034_auto_20190604_0909'),
        ('treasury', '0034_auto_20190403_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fi_docTraceLog', to='util.DocTraceLog'),
        ),
        migrations.AddField(
            model_name='fx',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fx_docTraceLog', to='util.DocTraceLog'),
        ),
        migrations.AddField(
            model_name='fxcli',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_fxcli_docTraceLog', to='util.DocTraceLog'),
        ),
        migrations.AddField(
            model_name='mm',
            name='docTraceLog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_mm_docTraceLog', to='util.DocTraceLog'),
        ),
    ]
