# Generated by Django 2.2.6 on 2020-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0036_auto_20190812_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='fi',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='fxcli',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
    ]
