# Generated by Django 2.2.6 on 2020-01-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0037_auto_20200114_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mm',
            name='ref_id',
        ),
    ]
