# Generated by Django 2.2.6 on 2020-01-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0038_remove_mm_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decot_pct', models.DecimalField(blank=True, decimal_places=4, default=1, help_text='Taux de Decot', max_digits=7, null=True, verbose_name='Decot')),
                ('dom_pct', models.DecimalField(blank=True, decimal_places=4, default=1, help_text='Pourcentage de Nantissement', max_digits=7, null=True, verbose_name='Pct Titre')),
                ('dom_pct_montant_lc', models.DecimalField(blank=True, decimal_places=0, help_text='Montant équivalent en F.CFA', max_digits=18, null=True, verbose_name='dom_pct_montant_lc')),
                ('obs', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('fi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_collateral_fi', to='treasury.FI', verbose_name='Fixed Income')),
                ('mm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_collateral_mm', to='treasury.MM', verbose_name='Money Market')),
            ],
            options={
                'verbose_name': 'Collateral Manager',
                'verbose_name_plural': 'Collateral Manager',
                'db_table': 'tresor_collateral',
                'managed': True,
                'unique_together': {('mm', 'fi')},
            },
        ),
        migrations.AddField(
            model_name='mm',
            name='collateral',
            field=models.ManyToManyField(related_name='treasury_mm_collateral', through='treasury.Collateral', to='treasury.FI', verbose_name='collateral'),
        ),
    ]
