# Generated by Django 2.2.6 on 2020-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0039_auto_20200116_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fi',
            name='repayment',
        ),
        migrations.AddField(
            model_name='fi',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'Aquisition", max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fi',
            name='taux',
            field=models.DecimalField(decimal_places=4, help_text='Coupon Rate', max_digits=8),
        ),
    ]
