# Generated by Django 2.2.6 on 2020-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0040_auto_20200116_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='dom_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pourcentage de Nantissement', max_digits=7, null=True, verbose_name='Pct Titre'),
        ),
    ]
