# Generated by Django 2.2.6 on 2020-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0041_auto_20200116_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='dom_pct_montant_lc',
            field=models.DecimalField(decimal_places=0, help_text='Montant équivalent en F.CFA', max_digits=18, verbose_name='dom_pct_montant_lc'),
        ),
    ]
