# Generated by Django 2.2.6 on 2020-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0043_auto_20200116_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='folio',
            field=models.IntegerField(choices=[(1, '\\PROP'), (2, '\\CLI')], default=1, help_text='Portefeuille Banque(Prop)/Client', verbose_name='Folio'),
        ),
    ]
