# Generated by Django 2.2.6 on 2020-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0045_auto_20200122_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='folio',
            field=models.IntegerField(choices=[(1, '\\PROP'), (2, '\\CLI'), (3, '\\COLT')], default=1, help_text='Portefeuille du titre', verbose_name='Folio'),
        ),
    ]
