# Generated by Django 2.2.6 on 2020-11-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0046_auto_20201002_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='price_pct',
            field=models.DecimalField(decimal_places=2, default=100, help_text="Prix d'Aquisition en %", max_digits=5),
            preserve_default=False,
        ),
    ]
