# Generated by Django 2.2.6 on 2020-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0047_fi_price_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='price_pct',
            field=models.DecimalField(decimal_places=4, help_text="Prix d'Aquisition en %", max_digits=7),
        ),
    ]
