# Generated by Django 2.2.6 on 2020-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0048_auto_20201109_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="-/+ frais/revenu totaux d'acquisition", max_digits=18, null=True),
        ),
    ]
