# Generated by Django 2.2.6 on 2020-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0049_fi_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi',
            name='coupon_couru',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'Aquisition", max_digits=18),
            preserve_default=False,
        ),
    ]
