# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccBalDetail',
            fields=[
                ('apbkcom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.ApBkcom')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
            ],
            options={
                'verbose_name': 'Accounting Balance Mgmt.',
                'db_table': 'ACC_BAL_DETAIL',
                'managed': True,
                'verbose_name_plural': 'Accounting Balance Mgmt.',
            },
            bases=('interface.apbkcom',),
        ),
        migrations.CreateModel(
            name='AccChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.IntegerField(db_column='CHAP')),
                ('category', models.CharField(db_column='CATEGORY', max_length=20)),
                ('init', models.CharField(db_column='INIT', max_length=200)),
            ],
        ),
    ]
