# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accbaldetail',
            name='ctrl',
            field=models.BooleanField(db_column='CTRL', default=False),
        ),
    ]
