# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accbaldetail_ctrl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accbaldetail',
            name='apbkcom_ptr',
        ),
        migrations.RemoveField(
            model_name='accbaldetail',
            name='client',
        ),
        migrations.DeleteModel(
            name='AccBalDetail',
        ),
    ]
