# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0004_auto_20171026_0918'),
        ('tiers', '0001_initial'),
        ('accounting', '0004_delete_accchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccBalDetail',
            fields=[
                ('apbkcom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.ApBkcom')),
                ('ctrl', models.BooleanField(db_column='CTRL', default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
            ],
            options={
                'verbose_name': 'Accounting Balance Mgmt.',
                'db_table': 'ACC_BAL_DETAIL',
                'managed': True,
                'verbose_name_plural': 'Accounting Balance Mgmt.',
            },
            bases=('interface.apbkcom',),
        ),
    ]
