# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
        ('interface', '0007_auto_20180321_1556'),
        ('accounting', '0005_accbaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('aptb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.ApTB')),
                ('clientCtrl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
            ],
            options={
                'verbose_name': 'Contrt\xf4le de TB',
                'db_table': 'ACC_TB',
                'managed': True,
                'verbose_name_plural': 'Contrt\xf4le de TB',
            },
            bases=('interface.aptb',),
        ),
        migrations.RemoveField(
            model_name='accbaldetail',
            name='apbkcom_ptr',
        ),
        migrations.RemoveField(
            model_name='accbaldetail',
            name='client',
        ),
        migrations.DeleteModel(
            name='AccBalDetail',
        ),
    ]
