# Generated by Django 2.1.5 on 2019-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180321_1556'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trialbalance',
            table='acc_tb',
        ),
    ]
