# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('id_AP', models.CharField(blank=True, max_length=3, null=True)),
                ('ccyPeg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
            ],
            options={
                'db_table': 'UTIL_CCY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CcyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=6, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('id_AP', models.CharField(blank=True, max_length=3, null=True)),
                ('ccy1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccy1', to='util.Ccy')),
                ('ccy2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccy2', to='util.Ccy')),
            ],
            options={
                'db_table': 'UTIL_CCYPAIR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'UTIL_WF_STATUT',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='ccypair',
            unique_together=set([('alias',)]),
        ),
    ]
