# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Type_Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('id_AP', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'UTIL_CATALOG_TYPE_COMM',
                'managed': True,
            },
        ),
    ]
