# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_catalog_type_commercial_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_commercial',
            name='nature',
            field=models.IntegerField(choices=[(0, 'Importation'), (1, 'Service'), (2, 'Particulier'), (99, 'Ind\xe9fini')], default=0),
        ),
    ]
