# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0004_auto_20170526_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_commercial',
            name='nature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
