# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0005_auto_20170526_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_type_commercial',
            options={'managed': True, 'verbose_name': 'Contr\xf4le de nomenclature commercial', 'verbose_name_plural': 'Contr\xf4le de nomenclature commercial'},
        ),
    ]
