# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0006_auto_20170530_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Type_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_l1', models.CharField(max_length=100)),
                ('category_l2', models.CharField(max_length=50)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Contr\xf4le de nomenclature document',
                'db_table': 'UTIL_CATALOG_TYPE_DOC',
                'managed': True,
                'verbose_name_plural': 'Contr\xf4le de nomenclature document',
            },
        ),
    ]
