# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0008_catalog_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_type_product',
            name='contentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
