# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_product',
            name='category_l1',
            field=models.CharField(max_length=50),
        ),
    ]
