# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0011_auto_20180326_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Type_Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_l1', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contr\xf4le de nomenclature Activit\xe9',
                'db_table': 'UTIL_CATALOG_TYPE_ACT',
                'managed': True,
                'verbose_name_plural': 'Contr\xf4le de nomenclature Activit\xe9',
            },
        ),
        migrations.AddField(
            model_name='catalog_type_product',
            name='category_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Act'),
        ),
    ]
