# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0012_auto_20180529_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_type_act',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
