# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0013_catalog_type_act_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_act',
            name='alias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalog_type_product',
            name='category_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Act'),
        ),
    ]
