# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0014_auto_20180529_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_type_doc',
            name='category_act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Act'),
            preserve_default=False,
        ),
    ]
