# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0015_catalog_type_doc_category_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog_type_doc',
            name='contentType',
        ),
        migrations.AlterField(
            model_name='catalog_type_doc',
            name='category_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Act'),
        ),
    ]
