# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0016_auto_20180529_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_type_doc',
            name='contentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
