# Generated by Django 2.1.5 on 2019-03-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0017_catalog_type_doc_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_doc',
            name='category_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Act'),
        ),
        migrations.AlterField(
            model_name='catalog_type_doc',
            name='contentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='ccy',
            name='ccyPeg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Ccy'),
        ),
        migrations.AlterField(
            model_name='ccypair',
            name='ccy1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_ccypair_ccy1', to='util.Ccy'),
        ),
        migrations.AlterField(
            model_name='ccypair',
            name='ccy2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_ccypair_ccy2', to='util.Ccy'),
        ),
    ]
