# Generated by Django 2.1.2 on 2019-03-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0020_auto_20190330_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogtypeproduct',
            options={'managed': True, 'ordering': ('content_type', 'category_l1'), 'verbose_name': 'Contrôle de nomenclature produit', 'verbose_name_plural': 'Contrôle de nomenclature produit'},
        ),
    ]
