# Generated by Django 2.1.2 on 2019-03-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0021_auto_20190330_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogtypefile',
            name='category_act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeActivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogtypefile',
            name='category_l2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
