# Generated by Django 2.1.5 on 2019-03-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0022_auto_20190330_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogtypeactivity',
            table='util_catalog_type_act',
        ),
        migrations.AlterModelTable(
            name='catalogtypecommercial',
            table='util_catalog_type_comm',
        ),
        migrations.AlterModelTable(
            name='catalogtypefile',
            table='util_catalog_type_doc',
        ),
        migrations.AlterModelTable(
            name='catalogtypeproduct',
            table='util_catalog_type_product',
        ),
        migrations.AlterModelTable(
            name='catalogtypetiers',
            table='util_catalog_type_tiers',
        ),
        migrations.AlterModelTable(
            name='ccy',
            table='util_ccy',
        ),
        migrations.AlterModelTable(
            name='ccypair',
            table='util_ccypair',
        ),
        migrations.AlterModelTable(
            name='statut',
            table='util_wf_statut',
        ),
    ]
