# Generated by Django 2.1.5 on 2019-04-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0023_auto_20190331_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogtypeproduct',
            name='child_type',
            field=models.ForeignKey(blank=True, help_text='Inline model content type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_catalogtypeproduct_child_type', to='contenttypes.ContentType', verbose_name='Child Type'),
        ),
        migrations.AlterField(
            model_name='catalogtypeproduct',
            name='content_type',
            field=models.ForeignKey(help_text='Parent model content type', on_delete=django.db.models.deletion.CASCADE, related_name='util_catalogtypeproduct_parent_type', to='contenttypes.ContentType', verbose_name='Parent Type'),
        ),
    ]
