# Generated by Django 2.1.5 on 2019-05-29 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0025_catalogtypeproduct_code_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTraceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creation', models.DateTimeField(blank=True, editable=False, help_text='Time Creation', null=True)),
                ('obs', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'util_doc_trace_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocTraceLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True)),
                ('chk_exp', models.BooleanField(default=False, help_text='Sending Agent', verbose_name='Chk Exp')),
                ('time_exp', models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True)),
                ('chk_recv', models.BooleanField(default=False, help_text='Receiving Agent', verbose_name='Chk Receive')),
                ('time_recv', models.DateTimeField(blank=True, editable=False, help_text='Time Receive', null=True)),
                ('docTraceLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_doctracelogdetail_docTraceLog', to='util.DocTraceLog')),
                ('oper_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_doctracelogdetail_exp', to=settings.AUTH_USER_MODEL)),
                ('oper_recv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_doctracelogdetail_recv', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_doctracelogdetail_statut', to='util.Statut')),
            ],
            options={
                'db_table': 'util_doc_trace_log_detail',
                'managed': True,
            },
        ),
    ]
