# Generated by Django 2.1.5 on 2019-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0027_auto_20190531_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctracelogdetail',
            name='obs',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
