# Generated by Django 2.1.5 on 2019-05-31 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0029_auto_20190531_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctracelog',
            old_name='time_creation',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='doctracelog',
            name='chk_create',
            field=models.BooleanField(default=False, help_text='Receiving Agent', verbose_name='Chk Create'),
        ),
        migrations.AddField(
            model_name='doctracelog',
            name='oper_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_doctracelog_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
