# Generated by Django 2.1.5 on 2019-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0030_auto_20190531_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctracelog',
            name='chk_create',
            field=models.BooleanField(default=False, help_text='Create Agent', verbose_name='Chk Create'),
        ),
    ]
