# Generated by Django 2.1.5 on 2019-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0031_auto_20190531_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctracelog',
            name='oper_create',
        ),
        migrations.AlterField(
            model_name='doctracelog',
            name='chk_create',
            field=models.BooleanField(default=False, help_text='Create Tracing Log', verbose_name='Chk Create'),
        ),
    ]
