# Generated by Django 2.1.5 on 2019-05-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0032_auto_20190531_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctracelogdetail',
            name='statut',
        ),
    ]
