# Generated by Django 2.1.5 on 2019-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0033_remove_doctracelogdetail_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctracelogdetail',
            name='chk_exp',
            field=models.BooleanField(default=False, help_text='Sending Agent', verbose_name='Chk Expédition'),
        ),
        migrations.AlterField(
            model_name='doctracelogdetail',
            name='chk_recv',
            field=models.BooleanField(default=False, help_text='Receiving Agent', verbose_name='Chk Réception'),
        ),
        migrations.AlterField(
            model_name='doctracelogdetail',
            name='time_exp',
            field=models.DateTimeField(blank=True, editable=False, help_text='Heure Expédition', null=True),
        ),
        migrations.AlterField(
            model_name='doctracelogdetail',
            name='time_recv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Heure Réception', null=True),
        ),
    ]
