# Generated by Django 2.1.5 on 2019-08-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0034_auto_20190604_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogtypefile',
            name='category_act',
        ),
    ]
