# Generated by Django 2.1.5 on 2019-08-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0035_remove_catalogtypefile_category_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_switch', models.CharField(blank=True, max_length=15, null=True)),
                ('obs', models.CharField(blank=True, max_length=15, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflow',
                'db_table': 'util_wf',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='statut',
            options={'managed': True, 'verbose_name': 'Workflow Status', 'verbose_name_plural': 'Workflow Status'},
        ),
        migrations.AddField(
            model_name='workflow',
            name='s_fnl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_workflow_fnl', to='util.Statut', verbose_name='Statut Final'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='s_init',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_workflow_init', to='util.Statut', verbose_name='Statut Initial'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('content_type', 's_init', 'chk_switch')},
        ),
    ]
