# Generated by Django 2.1.5 on 2019-08-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0036_auto_20190821_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='s_init',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='util_workflow_init', to='util.Statut', verbose_name='Statut Initial'),
        ),
    ]
