# Generated by Django 2.1.5 on 2019-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0037_auto_20190826_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogtypecommercial',
            name='jour_dom',
            field=models.IntegerField(blank=True, help_text="Nb.de jour pour l'apurement", null=True),
        ),
        migrations.AlterField(
            model_name='catalogtypeproduct',
            name='code_product',
            field=models.CharField(max_length=10, verbose_name='Code Product'),
        ),
    ]
