# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tiers.client.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0008_catalog_type_product'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCorresp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
                ('chk_active', models.BooleanField(default=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
            ],
            options={
                'db_table': 'THIRD_CORRESP_ACCOUNT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountCpty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
            ],
            options={
                'db_table': 'THIRD_CPTY_ACCOUNT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountDepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_DEPOSITORY_ACCOUNT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Autorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_AUTORITE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_BROKER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientCtrl',
            fields=[
                ('apbkcli_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.ApBkcli')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigle')),
            ],
            options={
                'verbose_name': 'Ctrl Client',
                'db_table': 'THIRD_CLIENT_CTRL',
                'managed': True,
                'verbose_name_plural': 'Ctrl Client',
            },
            bases=('interface.apbkcli',),
        ),
        migrations.CreateModel(
            name='ClientCtrlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(verbose_name='Date Valeur')),
                ('date_exp', models.DateField(verbose_name="Date d'Ech\xe9ance")),
                ('chk_actif', models.BooleanField(default=False, verbose_name='Chk_actif')),
                ('file', models.FileField(upload_to=tiers.client.models.upload_path_handler)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('clientCtrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Doc')),
                ('oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ctrl Client (T\xe9l\xe9chargement)',
                'db_table': 'THIRD_CLIENT_CTRL_FILE',
                'managed': True,
                'verbose_name_plural': 'Ctrl Client (T\xe9l\xe9chargement)',
            },
        ),
        migrations.CreateModel(
            name='ClientFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('feeName', models.CharField(db_column='FEE_NAME', max_length=100)),
                ('feeType', models.IntegerField(choices=[(0, 'Commission'), (1, 'Surcote'), (2, 'Quota')], db_column='FEE_TYPE', default=0)),
                ('feeValueType', models.IntegerField(choices=[(0, 'in Value'), (1, 'in %')], db_column='FEE_VAL_TYPE', default=0)),
                ('feeValue', models.DecimalField(db_column='FEE_VAL', decimal_places=2, max_digits=18)),
                ('date_valeur', models.DateField(verbose_name='Date en Vigeur')),
                ('date_exp', models.DateField(verbose_name="Date d'\xe9ch\xe9ance")),
                ('chk_actif', models.BooleanField(default=False, verbose_name='Chk_actif')),
                ('file', models.FileField(upload_to=tiers.client.models.upload_path_handler)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'General Fee Ctrl',
                'db_table': 'FEE_CTRL',
                'managed': True,
                'verbose_name_plural': 'General Fee Ctrl',
            },
        ),
        migrations.CreateModel(
            name='Corresp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(0, 'Agence'), (1, 'Correspondant')], default=1)),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_CORRESP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cpty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_CPTY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Depository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_DEPOSITORY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Emetteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_EMETTEUR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_ap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'THIRD_MARKET',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accountdepository',
            name='depository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiers.Depository'),
        ),
        migrations.AddField(
            model_name='accountcpty',
            name='cpty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiers.Cpty'),
        ),
        migrations.AddField(
            model_name='accountcorresp',
            name='corresp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.Corresp'),
        ),
        migrations.AlterUniqueTogether(
            name='accountcorresp',
            unique_together=set([('corresp', 'alias')]),
        ),
    ]
