# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_auto_20180323_1234'),
        ('treasury', '0006_auto_20180323_1234'),
        ('util', '0010_catalog_type_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientctrl',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='nature',
            field=models.IntegerField(choices=[(0, 'Agence'), (1, 'Corresp')], default=1),
        ),
        migrations.DeleteModel(
            name='AccountCpty',
        ),
        migrations.DeleteModel(
            name='AccountDepository',
        ),
        migrations.DeleteModel(
            name='Cpty',
        ),
        migrations.DeleteModel(
            name='Depository',
        ),
        migrations.AddField(
            model_name='tiersctrl',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
        migrations.AddField(
            model_name='corresp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.TiersCtrl'),
        ),
    ]
