# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_auto_20180323_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiersctrl',
            options={'managed': True, 'verbose_name': 'Ctrl Tiers', 'verbose_name_plural': 'Ctrl Tiers'},
        ),
        migrations.RemoveField(
            model_name='clientctrl',
            name='tiers',
        ),
    ]
