# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0005_auto_20180323_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiersctrl',
            name='tiers',
        ),
    ]
