# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0006_remove_tiersctrl_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiersctrl',
            name='tiers',
            field=models.BooleanField(default=False, verbose_name='Tiers'),
        ),
    ]
