# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0008_auto_20180323_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiersctrl',
            name='apbkcli_ptr',
        ),
        migrations.RemoveField(
            model_name='tiersctrl',
            name='nature',
        ),
        migrations.AlterField(
            model_name='corresp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl'),
        ),
        migrations.DeleteModel(
            name='TiersCtrl',
        ),
    ]
