# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_auto_20180323_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corresp',
            name='profile',
        ),
    ]
