# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('tiers', '0010_remove_corresp_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiersCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCtrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers')),
            ],
            options={
                'verbose_name': 'Ctrl Tiers',
                'db_table': 'THIRD_TIERS_CTRL',
                'managed': True,
                'verbose_name_plural': 'Ctrl Tiers',
            },
        ),
        migrations.RemoveField(
            model_name='clientfee',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ClientFee',
        ),
    ]
