# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0011_auto_20180323_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiersctrl',
            name='clientCtrl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl'),
        ),
    ]
