# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0012_auto_20180324_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiersctrl',
            name='nature',
        ),
    ]
