# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('tiers', '0014_auto_20180324_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientctrlfile',
            old_name='nature',
            new_name='type_doc',
        ),
        migrations.RemoveField(
            model_name='clientctrl',
            name='tiers',
        ),
        migrations.RemoveField(
            model_name='corresp',
            name='nature',
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='type_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_client', to='util.Catalog_Type_Tiers'),
        ),
        migrations.AddField(
            model_name='corresp',
            name='clientCtrl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl'),
        ),
        migrations.AddField(
            model_name='corresp',
            name='type_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_tiers', to='util.Catalog_Type_Tiers'),
        ),
    ]
