# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0016_auto_20180324_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corresp',
            options={'managed': True, 'verbose_name': 'Ctrl Corresp', 'verbose_name_plural': 'Ctrl Corresp'},
        ),
    ]
