# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('tiers', '0017_auto_20180324_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
                ('clientCtrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
                ('type_tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers')),
            ],
            options={
                'verbose_name': 'Ctrl Cpty',
                'db_table': 'THIRD_Cpty',
                'managed': True,
                'verbose_name_plural': 'Ctrl Cpty',
            },
        ),
        migrations.AlterField(
            model_name='corresp',
            name='type_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
    ]
