# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0018_auto_20180324_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corresp',
            options={'managed': True, 'verbose_name': 'Ctrl Treasury Unit', 'verbose_name_plural': 'Ctrl Treasury Unit'},
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='chk_corresp',
            field=models.BooleanField(default=False, verbose_name='Treasury Unit'),
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='chk_cpty',
            field=models.BooleanField(default=False, verbose_name='Counterparty'),
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='chk_depo',
            field=models.BooleanField(default=False, verbose_name='Depository'),
        ),
    ]
