# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0019_auto_20180324_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpty',
            options={'managed': True, 'verbose_name': 'Ctrl Counterparty', 'verbose_name_plural': 'Ctrl Counterparty'},
        ),
        migrations.AlterField(
            model_name='clientctrl',
            name='type_client',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_client', to='util.Catalog_Type_Tiers'),
        ),
    ]
