# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_catalog_type_tiers'),
        ('tiers', '0020_auto_20180324_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('chk_active', models.BooleanField(default=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Ccy')),
            ],
            options={
                'db_table': 'THIRD_DEPO_ACC',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
                ('clientCtrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
                ('type_tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers')),
            ],
            options={
                'verbose_name': 'Ctrl Depository',
                'db_table': 'THIRD_DEPO',
                'managed': True,
                'verbose_name_plural': 'Ctrl Depository',
            },
        ),
        migrations.AddField(
            model_name='accountdepo',
            name='depo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.Depo'),
        ),
        migrations.AlterUniqueTogether(
            name='accountdepo',
            unique_together=set([('depo', 'alias')]),
        ),
    ]
