# Generated by Django 2.1.5 on 2019-03-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0022_auto_20180326_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientctrl',
            name='type_client',
            field=models.ForeignKey(blank=True, default=7, limit_choices_to={'contentType': 109}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers_clientctrl_type_client', to='util.Catalog_Type_Tiers'),
        ),
        migrations.AlterField(
            model_name='clientctrlfile',
            name='type_doc',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 109}, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Doc'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 18}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
        migrations.AlterField(
            model_name='cpty',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 32}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
        migrations.AlterField(
            model_name='depo',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'contentType': 130}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.Catalog_Type_Tiers'),
        ),
    ]
