# Generated by Django 2.1.2 on 2019-03-29 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util.fileStorage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0020_auto_20190330_0404'),
        ('tiers', '0023_auto_20190318_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fileName', models.CharField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to=util.fileStorage.models.upload_path_handler)),
            ],
            options={
                'verbose_name': 'Client file storage',
                'verbose_name_plural': 'Client file storage',
                'db_table': 'THIRD_CLIENT_FILE',
                'ordering': ('client', 'type_file', '-id'),
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='clientctrl',
            options={'managed': True, 'ordering': ('ref_id',), 'verbose_name': 'Ctrl Client', 'verbose_name_plural': 'Ctrl Client'},
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='oper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corresp',
            name='chk_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientctrl',
            name='type_client',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers_clientctrl_type_client', to='util.CatalogTypeTiers'),
        ),
        migrations.AlterField(
            model_name='clientctrlfile',
            name='type_doc',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 109}, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeFile'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 18}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeTiers'),
        ),
        migrations.AlterField(
            model_name='cpty',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 32}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeTiers'),
        ),
        migrations.AlterField(
            model_name='depo',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 130}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeTiers'),
        ),
        migrations.AddField(
            model_name='clientfilestorage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.ClientCtrl'),
        ),
        migrations.AddField(
            model_name='clientfilestorage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='clientfilestorage',
            name='oper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers_clientfilestorage_oper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfilestorage',
            name='type_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeFile'),
        ),
    ]
