# Generated by Django 2.1.2 on 2019-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0024_auto_20190330_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientctrlfile',
            name='clientCtrl',
        ),
        migrations.RemoveField(
            model_name='clientctrlfile',
            name='oper',
        ),
        migrations.RemoveField(
            model_name='clientctrlfile',
            name='type_doc',
        ),
        migrations.DeleteModel(
            name='ClientCtrlFile',
        ),
    ]
