# Generated by Django 2.1.2 on 2019-03-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('tiers', '0025_auto_20190330_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfilestorage',
            name='group_oper',
            field=models.ForeignKey(blank=True, help_text='Group propriétaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers_clientfilestorage_group_oper', to='auth.Group', verbose_name='Created by'),
        ),
    ]
