# Generated by Django 2.1.5 on 2019-03-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0028_auto_20190331_0131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountcorresp',
            table='third_corresp_account',
        ),
        migrations.AlterModelTable(
            name='corresp',
            table='third_corresp',
        ),
    ]
