# Generated by Django 2.1.5 on 2019-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0029_auto_20190331_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountdepo',
            table='third_depo_acc',
        ),
        migrations.AlterModelTable(
            name='clientctrl',
            table='third_cliend_ctrl',
        ),
        migrations.AlterModelTable(
            name='clientfilestorage',
            table='third_client_file',
        ),
        migrations.AlterModelTable(
            name='cpty',
            table='third_cpty',
        ),
        migrations.AlterModelTable(
            name='depo',
            table='third_depo',
        ),
    ]
