# Generated by Django 2.1.5 on 2019-03-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0030_auto_20190331_1623'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientctrl',
            table='third_client_ctrl',
        ),
    ]
