# Generated by Django 2.1.5 on 2019-04-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0031_auto_20190331_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfilestorage',
            name='type_file',
            field=models.ForeignKey(blank=True, help_text='Type du document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='util.CatalogTypeFile', verbose_name='type_file'),
        ),
    ]
