# Generated by Django 2.1.5 on 2019-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0032_auto_20190403_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfilestorage',
            name='obs',
        ),
    ]
