# Generated by Django 2.1.5 on 2019-08-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0033_remove_clientfilestorage_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientctrl',
            old_name='address',
            new_name='obs',
        ),
        migrations.AddField(
            model_name='clientctrl',
            name='niu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIU'),
        ),
        migrations.AlterField(
            model_name='clientctrl',
            name='alias',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='clientfilestorage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl'),
        ),
    ]
