# Generated by Django 2.1.5 on 2019-09-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0036_clientctrl_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientctrl',
            name='email',
            field=models.CharField(blank=True, default=None, help_text='Addresse Mail Electronique', max_length=100, null=True, verbose_name='Email'),
        ),
    ]
