# Generated by Django 2.2.6 on 2020-11-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0037_auto_20190913_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresp',
            name='type_tiers',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 18}, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeTiers'),
        ),
    ]
