# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 09:15
from __future__ import unicode_literals

import bureau.gestion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0008_catalog_type_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recu', models.DateField(verbose_name='Date re\xe7u')),
                ('dossier', models.CharField(max_length=50, verbose_name='Nom du document')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('file_v0', models.FileField()),
                ('date_limit', models.DateField(verbose_name='Date de limite')),
                ('verifChk', models.BooleanField(default=False, help_text='Ctrl de la version finale', verbose_name='Chk termination')),
                ('verifChkDate', models.DateField(blank=True, null=True, verbose_name='Date de la termination')),
                ('file_vf', models.FileField(blank=True, null=True)),
                ('agentChk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentChk', to=settings.AUTH_USER_MODEL, verbose_name='Agent de Finalisation')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestion du projet de traduction',
                'db_table': 'BUREAU_DOC',
                'managed': True,
                'verbose_name_plural': 'Gestion des projets de traduction',
            },
        ),
        migrations.CreateModel(
            name='InternalDocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20, verbose_name='D\xe9scription du fichier')),
                ('date_limit', models.DateField(blank=True, null=True, verbose_name='Date de limite')),
                ('date_upload', models.DateField(blank=True, null=True, verbose_name="Date d'actualisation")),
                ('file', models.FileField(blank=True, null=True,)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation du fichier')),
                ('agent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent1', to=settings.AUTH_USER_MODEL, verbose_name='Traduction')),
                ('agent2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent2', to=settings.AUTH_USER_MODEL, verbose_name='Verification')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureau.InternalDoc', verbose_name='Num\xe9ro du dossier')),
            ],
            options={
                'verbose_name': 'Gestion du fichier de traduction',
                'db_table': 'BUREAU_DOC_FILE',
                'managed': True,
                'verbose_name_plural': 'Gestion des fichiers de traduction',
            },
        ),
        migrations.CreateModel(
            name='InternalDocNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, verbose_name="Nom de l'activit\xe9")),
                ('obs', models.TextField(blank=True, null=True, verbose_name="Observation de l'activit\xe9")),
            ],
            options={
                'verbose_name': 'Gestion de la nature du document',
                'db_table': 'BUREAU_DOC_NATURE',
                'managed': True,
                'verbose_name_plural': 'Gestion de la nature du document',
            },
        ),
        migrations.AddField(
            model_name='internaldoc',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureau.InternalDocNature', verbose_name='Nature'),
        ),
        migrations.AddField(
            model_name='internaldoc',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internalDocStatut', to='util.Statut'),
        ),
    ]
