# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 08:00
from __future__ import unicode_literals

import bureau.gestion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0011_auto_20180326_1157'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bureau', '0002_auto_20180529_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(verbose_name='Date de cr\xe9ation')),
                ('dossier', models.CharField(max_length=100, verbose_name='Nom du dossier')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Doc', verbose_name='Nature')),
                ('uti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_uti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestion du dossier interne',
                'db_table': 'BUREAU_DOC',
                'managed': True,
                'verbose_name_plural': 'Gestion du dossier interne',
            },
        ),
        migrations.CreateModel(
            name='InternalDocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(verbose_name='Date de cr\xe9ation')),
                ('desc', models.CharField(max_length=100, verbose_name='Document')),
                ('file', models.FileField(blank=True, null=True)),
                ('chk_actif', models.BooleanField(default=False, verbose_name='En Vigeur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureau.InternalDoc', verbose_name='Num\xe9ro du dossier')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.Catalog_Type_Doc', verbose_name='Nature')),
                ('uti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_uti', to=settings.AUTH_USER_MODEL, verbose_name='UTI')),
            ],
            options={
                'verbose_name': 'Gestion du document t\xe9l\xe9charg\xe9',
                'db_table': 'BUREAU_DOC_FILE',
                'managed': True,
                'verbose_name_plural': 'Gestion du document t\xe9l\xe9charg\xe9',
            },
        ),
    ]
