# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0015_catalog_type_doc_category_act'),
        ('bureau', '0003_internaldoc_internaldocfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldoc',
            name='category_act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_category_act', to='util.Catalog_Type_Act'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaldoc',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_category_product', to='util.Catalog_Type_Product'),
        ),
        migrations.AddField(
            model_name='internaldocfile',
            name='category_act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_category_act', to='util.Catalog_Type_Act'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaldocfile',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_category_product', to='util.Catalog_Type_Product'),
        ),
        migrations.AlterField(
            model_name='internaldoc',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_nature', to='util.Catalog_Type_Doc'),
        ),
        migrations.AlterField(
            model_name='internaldocfile',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_nature', to='util.Catalog_Type_Doc'),
        ),
    ]
