# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0004_auto_20180529_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaldocfile',
            options={'managed': True, 'verbose_name': 'Gestion du document interne', 'verbose_name_plural': 'Gestion du document interne'},
        ),
    ]
