# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0006_auto_20180529_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaldocfile',
            name='group',
        ),
    ]
