# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('bureau', '0007_remove_internaldocfile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldocfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_group', to='auth.Group'),
        ),
    ]
