# Generated by Django 2.1.2 on 2018-10-10 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0008_internaldocfile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldoc',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internaldoc_category_product', to='util.Catalog_Type_Product'),
        ),
        migrations.AlterField(
            model_name='internaldoc',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internaldoc_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='internaldoc',
            name='nature',
            field=models.ForeignKey(limit_choices_to={'contentType': 55}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_nature', to='util.Catalog_Type_Doc'),
        ),
        migrations.AlterField(
            model_name='internaldoc',
            name='uti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internaldoc_uti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internaldocfile',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internaldocfile_category_product', to='util.Catalog_Type_Product'),
        ),
        migrations.AlterField(
            model_name='internaldocfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internaldocfile_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='internaldocfile',
            name='nature',
            field=models.ForeignKey(limit_choices_to={'contentType': 57}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_nature', to='util.Catalog_Type_Doc'),
        ),
    ]
