# Generated by Django 2.1.2 on 2019-03-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0009_auto_20181010_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldoc',
            name='nature',
            field=models.ForeignKey(limit_choices_to={'content_type': 55}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldoc_nature', to='util.CatalogTypeFile'),
        ),
        migrations.AlterField(
            model_name='internaldocfile',
            name='nature',
            field=models.ForeignKey(limit_choices_to={'content_type': 57}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internaldocfile_nature', to='util.CatalogTypeFile'),
        ),
    ]
