# Generated by Django 2.1.2 on 2019-03-30 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util.fileStorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('util', '0022_auto_20190330_1743'),
        ('bureau', '0010_auto_20190330_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fileName', models.CharField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to=util.fileStorage.models.upload_path_handler)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_group', to='auth.Group', verbose_name='Group')),
                ('oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internalfilestorage_oper', to=settings.AUTH_USER_MODEL)),
                ('type_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.CatalogTypeFile')),
            ],
            options={
                'verbose_name': 'Internal file storage',
                'verbose_name_plural': 'Internal file storage',
                'db_table': 'INTERNAL_FILE',
                'ordering': ('group', 'type_file', '-id'),
                'managed': True,
            },
        ),
    ]
