# Generated by Django 2.1.2 on 2019-03-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0011_internalfilestorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaldocfile',
            name='category_act',
        ),
        migrations.RemoveField(
            model_name='internaldocfile',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='internaldocfile',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='internaldocfile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internaldocfile',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='internaldocfile',
            name='uti',
        ),
        migrations.DeleteModel(
            name='InternalDocFile',
        ),
    ]
