# Generated by Django 2.1.2 on 2019-03-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('util', '0022_auto_20190330_1743'),
        ('bureau', '0012_auto_20190330_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalFileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(verbose_name='Date de création')),
                ('dossier', models.CharField(max_length=100, verbose_name='Nom du dossier')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('category_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internalfilefolder_category_act', to='util.CatalogTypeActivity')),
                ('category_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_category_product', to='util.CatalogTypeProduct')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_group', to='auth.Group')),
                ('nature', models.ForeignKey(limit_choices_to={'content_type': 55}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internalfilefolder_nature', to='util.CatalogTypeFile')),
                ('uti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_uti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestion du dossier interne',
                'verbose_name_plural': 'Gestion du dossier interne',
                'db_table': 'BUREAU_DOC',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='category_act',
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='uti',
        ),
        migrations.DeleteModel(
            name='InternalDoc',
        ),
    ]
