# Generated by Django 2.1.2 on 2019-03-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0013_auto_20190330_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalfilefolder',
            name='category_act',
        ),
        migrations.RemoveField(
            model_name='internalfilefolder',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='internalfilefolder',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internalfilefolder',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='internalfilefolder',
            name='uti',
        ),
        migrations.DeleteModel(
            name='InternalFileFolder',
        ),
    ]
