# Generated by Django 2.1.2 on 2019-03-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0014_auto_20190330_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='oper',
        ),
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='type_file',
        ),
        migrations.DeleteModel(
            name='InternalFileStorage',
        ),
    ]
