# Generated by Django 2.1.2 on 2019-03-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0022_auto_20190330_1743'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('bureau', '0015_auto_20190331_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalFileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('folderName', models.CharField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group_disrib', models.ManyToManyField(blank=True, help_text='Champs de Circulation', null=True, related_name='bureau_internalfilefolder_group_disrib', to='auth.Group', verbose_name='Available for')),
                ('group_oper', models.ForeignKey(blank=True, help_text='Group propriétaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_group_oper', to='auth.Group', verbose_name='Created by')),
                ('oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_internalfilefolder_oper', to=settings.AUTH_USER_MODEL, verbose_name='Oper')),
                ('type_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_type_file', to='util.CatalogTypeFile')),
            ],
            options={
                'verbose_name': 'Receuil des dossiers interne',
                'verbose_name_plural': 'Receuil des dossiers interne',
                'db_table': 'INTERNAL_FILE_FOLDER',
                'ordering': ('group_owner', 'type_folder', '-id'),
                'managed': True,
            },
        ),
    ]
