# Generated by Django 2.1.2 on 2019-03-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0017_internalfilestorage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalfilefolder',
            options={'managed': True, 'ordering': ('group_oper', 'type_folder', '-id'), 'verbose_name': 'Receuil des dossiers interne', 'verbose_name_plural': 'Receuil des dossiers interne'},
        ),
        migrations.AlterModelOptions(
            name='internalfilestorage',
            options={'managed': True, 'ordering': ('group_oper', 'type_file', '-id'), 'verbose_name': 'Receuil des fichier interne', 'verbose_name_plural': 'Receuil des fichier interne'},
        ),
        migrations.AlterField(
            model_name='internalfilefolder',
            name='group_disrib',
            field=models.ManyToManyField(help_text='Champs de Circulation', related_name='bureau_internalfilefolder_group_disrib', to='auth.Group', verbose_name='Available for'),
        ),
    ]
