# Generated by Django 2.1.2 on 2019-03-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0018_auto_20190331_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilefolder',
            name='group_disrib',
            field=models.ManyToManyField(help_text='Champs de Circulation', related_name='bureau_internalfilefolder_group_disrib', to='auth.Group', verbose_name='group_disrib'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='filefolder',
            field=models.ForeignKey(blank=True, help_text='Chrono de dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_filefolder', to='bureau.InternalFileFolder', verbose_name='File folder'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='group_oper',
            field=models.ForeignKey(blank=True, help_text='Group propriétaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_group_oper', to='auth.Group', verbose_name='group_oper'),
        ),
    ]
