# Generated by Django 2.1.2 on 2019-03-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0019_auto_20190331_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilefolder',
            name='group_oper',
            field=models.ForeignKey(blank=True, help_text='Group propriétaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilefolder_group_oper', to='auth.Group', verbose_name='group_oper'),
        ),
    ]
