# Generated by Django 2.1.2 on 2019-03-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0020_auto_20190331_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalfilefolder',
            old_name='folderName',
            new_name='folder_name',
        ),
        migrations.RenameField(
            model_name='internalfilestorage',
            old_name='fileName',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='filefolder',
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='file_folder',
            field=models.ForeignKey(blank=True, help_text='Chrono de dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_file_folder', to='bureau.InternalFileFolder', verbose_name='File folder'),
        ),
    ]
