# Generated by Django 2.1.5 on 2019-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0021_auto_20190331_0131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internalfilefolder',
            table='internal_file_folder',
        ),
        migrations.AlterModelTable(
            name='internalfilestorage',
            table='internal_file',
        ),
    ]
