# Generated by Django 2.1.5 on 2019-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0022_auto_20190331_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfilestorage',
            name='ref_id',
            field=models.CharField(blank=True, help_text='Référence id interne', max_length=10, null=True, verbose_name='Réf.ID'),
        ),
        migrations.AlterField(
            model_name='internalfilefolder',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
