# Generated by Django 2.1.5 on 2019-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0023_auto_20190402_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfilefolder',
            name='ref_id',
            field=models.CharField(blank=True, help_text='Référence id interne', max_length=10, null=True, verbose_name='Réf.ID'),
        ),
    ]
