# Generated by Django 2.1.5 on 2019-04-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0025_auto_20190403_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalfilefolder',
            options={'managed': True, 'ordering': ('group_oper', 'type_folder', '-id'), 'verbose_name': 'Classeur Interne', 'verbose_name_plural': 'Classeurs Internes'},
        ),
        migrations.AlterModelOptions(
            name='internalfilestorage',
            options={'managed': True, 'ordering': ('group_oper', 'type_file', '-id'), 'verbose_name': 'Document Interne', 'verbose_name_plural': 'Documents Internes'},
        ),
    ]
