# Generated by Django 2.1.5 on 2019-06-19 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bureau', '0027_auto_20190618_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfilestorage',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Chk Approv'),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Chk Verify'),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='date_recu',
            field=models.DateField(blank=True, help_text='Date de réception du document', null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='date_val',
            field=models.DateField(blank=True, help_text='Date de limite pour le traitement du document', null=True, verbose_name='Date de limite'),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='oper_approv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_approv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='oper_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_verify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='time_approv',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Approv', null=True),
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='time_verify',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time Verify', null=True),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='file_folder',
            field=models.ForeignKey(blank=True, help_text='Classeur de dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_file_folder', to='bureau.InternalFileFolder', verbose_name='File folder'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
