# Generated by Django 2.1.5 on 2019-06-19 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0028_auto_20190619_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilestorage',
            name='date_recu',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date de réception du document', verbose_name='Date de réception'),
            preserve_default=False,
        ),
    ]
