# Generated by Django 2.1.5 on 2019-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('bureau', '0029_auto_20190619_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalfilefolder',
            options={'managed': True, 'ordering': ('group_oper', 'type_folder', 'ref_id'), 'verbose_name': 'Classeur Interne', 'verbose_name_plural': 'Classeurs Internes'},
        ),
        migrations.AlterModelOptions(
            name='internalfilestorage',
            options={'managed': True, 'ordering': ('group_oper', 'type_file', 'ref_id'), 'verbose_name': 'Document Interne', 'verbose_name_plural': 'Documents Internes'},
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='group_disrib',
            field=models.ManyToManyField(help_text='Champs de Circulation', related_name='bureau_internalfilestorage_group_disrib', to='auth.Group', verbose_name='group_disrib'),
        ),
    ]
