# Generated by Django 2.1.5 on 2019-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0030_auto_20190619_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilestorage',
            name='group_disrib',
            field=models.ManyToManyField(blank=True, help_text='Champs de Circulation', null=True, related_name='bureau_internalfilestorage_group_disrib', to='auth.Group', verbose_name='group_disrib'),
        ),
    ]
