# Generated by Django 2.1.5 on 2019-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0031_auto_20190619_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilestorage',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Approv'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verify'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='ref_id',
            field=models.CharField(blank=True, help_text='Réf.ID interne', max_length=15, null=True, verbose_name='Réf.ID'),
        ),
    ]
