# Generated by Django 2.2.6 on 2019-11-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('bureau', '0032_auto_20190812_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalfilestorage',
            name='group_disrib',
        ),
        migrations.AddField(
            model_name='internalfilestorage',
            name='group_disrib',
            field=models.ForeignKey(blank=True, help_text='Champs de Circulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_internalfilestorage_group_disrib', to='auth.Group', verbose_name='group_disrib'),
        ),
    ]
