# Generated by Django 2.2.6 on 2019-11-06 16:03

import bureau.sca.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('tiers', '0037_auto_20190913_0748'),
        ('bureau', '0033_auto_20191101_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_val', models.DateField(verbose_name='Date de tenue')),
                ('date_exec', models.DateField(blank=True, null=True, verbose_name='Date Exec')),
            ],
            options={
                'verbose_name': 'Meeting Manager',
                'verbose_name_plural': 'Meeting Manager',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingUserType')),
            ],
            options={
                'verbose_name': 'Meeting User Type',
                'verbose_name_plural': 'Meeting User Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.ClientCtrl')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingUserType')),
            ],
            options={
                'verbose_name': 'Meeting User',
                'verbose_name_plural': 'Meeting User',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingType')),
            ],
            options={
                'verbose_name': 'Meeting Type',
                'verbose_name_plural': 'Meeting Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingItemType')),
            ],
            options={
                'verbose_name': 'Meeting Item Type',
                'verbose_name_plural': 'Meeting Item Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=0)),
                ('global_no', models.IntegerField(default=0)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('name_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.Meeting')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingItemType')),
            ],
            options={
                'verbose_name': 'Meeting Item',
                'verbose_name_plural': 'Meeting Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingDocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingDocType')),
            ],
            options={
                'verbose_name': 'Meeting File Type',
                'verbose_name_plural': 'Meeting File Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('name_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('file_fr', models.FileField(upload_to=bureau.sca.models.upload_path_handler)),
                ('file_cn', models.FileField(upload_to=bureau.sca.models.upload_path_handler)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.Meeting')),
                ('meeting_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingItem')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingDocType')),
                ('parent_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingDoc')),
            ],
            options={
                'verbose_name': 'Meeting Doc',
                'verbose_name_plural': 'Meeting Doc',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.MeetingType'),
        ),
    ]
