# Generated by Django 2.2.6 on 2019-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0034_auto_20191106_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingdoctype',
            options={'managed': True, 'verbose_name': 'Meeting Doc Type', 'verbose_name_plural': 'Meeting Doc Type'},
        ),
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='alias',
            new_name='alias_cn',
        ),
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='nature',
            new_name='alias_fr',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='alias',
            new_name='alias_cn',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='nature',
            new_name='alias_fr',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='alias',
            new_name='alias_cn',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='nature',
            new_name='alias_fr',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='alias',
            new_name='alias_cn',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='nature',
            new_name='alias_fr',
        ),
        migrations.AddField(
            model_name='meetingdoctype',
            name='nature_cn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingdoctype',
            name='nature_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingitemtype',
            name='nature_cn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingitemtype',
            name='nature_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='nature_cn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='nature_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingusertype',
            name='nature_cn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingusertype',
            name='nature_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
