# Generated by Django 2.2.6 on 2019-11-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0035_auto_20191106_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='alias_cn',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='alias_fr',
            new_name='name_cn',
        ),
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='nature_cn',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='meetingdoctype',
            old_name='nature_fr',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='alias_cn',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='alias_fr',
            new_name='name_cn',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='nature_cn',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='meetingitemtype',
            old_name='nature_fr',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='alias_cn',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='alias_fr',
            new_name='name_cn',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='nature_cn',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='nature_fr',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='alias_cn',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='alias_fr',
            new_name='name_cn',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='nature_cn',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='meetingusertype',
            old_name='nature_fr',
            new_name='nature',
        ),
    ]
