# Generated by Django 2.2.6 on 2019-11-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('util', '0038_auto_20190903_1706'),
        ('tiers', '0037_auto_20190913_0748'),
        ('transfert', '0094_auto_20191106_1703'),
        ('settlement', '0015_auto_20190812_1158'),
        ('treasury', '0036_auto_20190812_1158'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('bureau', '0036_auto_20191106_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingUser',
        ),
    ]
