# Generated by Django 2.2.6 on 2019-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0038_meetinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_exec',
        ),
        migrations.AddField(
            model_name='meeting',
            name='acc_period',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='global_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='name_cn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='name_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
