# Generated by Django 2.2.6 on 2019-11-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0039_auto_20191106_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='name_cn',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='name_fr',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
