# Generated by Django 2.2.6 on 2019-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0040_auto_20191107_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtype',
            name='alias',
            field=models.CharField(max_length=10),
        ),
    ]
