# Generated by Django 2.2.6 on 2019-11-07 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0042_auto_20191107_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='date_val',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de tenue'),
            preserve_default=False,
        ),
    ]
