# Generated by Django 2.2.6 on 2019-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0043_meetingitem_date_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='date_val',
            field=models.DateField(blank=True, null=True, verbose_name='Date de tenue'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='name_cn',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='name_fr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
