# Generated by Django 2.2.6 on 2019-11-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0045_auto_20191107_1007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingitem',
            unique_together={('meeting', 'order_no')},
        ),
    ]
