# Generated by Django 2.2.6 on 2019-11-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0046_auto_20191107_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'managed': True, 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='meetingdoctype',
            options={'managed': True, 'verbose_name': 'Meeting Doc Type', 'verbose_name_plural': 'Meeting Doc Types'},
        ),
        migrations.AlterModelOptions(
            name='meetingitem',
            options={'managed': True, 'verbose_name': 'Meeting Item', 'verbose_name_plural': 'Meeting Items'},
        ),
        migrations.AlterModelOptions(
            name='meetingitemtype',
            options={'managed': True, 'verbose_name': 'Meeting Item Type', 'verbose_name_plural': 'Meeting Item Types'},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={'managed': True, 'verbose_name': 'Meeting Type', 'verbose_name_plural': 'Meeting Types'},
        ),
        migrations.AlterModelOptions(
            name='meetingusertype',
            options={'managed': True, 'verbose_name': 'Meeting User Type', 'verbose_name_plural': 'Meeting User Types'},
        ),
    ]
