# Generated by Django 2.2.6 on 2019-11-07 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('bureau', '0047_auto_20191107_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdoc',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingdoc',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingdoc',
            name='group_oper',
            field=models.ForeignKey(blank=True, help_text='Group propriétaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_meetingdoc_group_oper', to='auth.Group', verbose_name='group_oper'),
        ),
        migrations.AddField(
            model_name='meetingdoc',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingdoc',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingdoc',
            name='oper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_meetingdoc_oper', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='nature',
            field=models.ForeignKey(blank=True, help_text='Type du document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_meetingdoc_nature', to='util.CatalogTypeFile', verbose_name='type_file'),
        ),
        migrations.DeleteModel(
            name='MeetingDocType',
        ),
    ]
