# Generated by Django 2.2.6 on 2019-11-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0049_meetingdoc_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdoc',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='name_cn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='name_fr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
