# Generated by Django 2.2.6 on 2019-11-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0050_auto_20191107_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingitem',
            name='date_val',
        ),
    ]
