# Generated by Django 2.2.6 on 2019-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0054_auto_20191107_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingitem',
            name='global_no',
        ),
        migrations.AddField(
            model_name='meeting',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='ref_no',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name_cn',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name_fr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='obs',
            field=models.TextField(blank=True, default='Responsable/责任部门: ', max_length=1000, null=True),
        ),
    ]
