# Generated by Django 2.2.6 on 2019-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0056_auto_20191107_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingitemtype',
            name='alias',
        ),
        migrations.AddField(
            model_name='meetingitemtype',
            name='item_key',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='obs',
            field=models.TextField(blank=True, default='Respo/责任部门: ', max_length=1000, null=True),
        ),
    ]
