# Generated by Django 2.2.6 on 2019-11-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0057_auto_20191107_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'managed': True, 'ordering': ['-date_val'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
    ]
