# Generated by Django 2.2.6 on 2019-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0058_auto_20191107_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='type_session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='nature',
            field=models.CharField(max_length=50),
        ),
    ]
