# Generated by Django 2.2.6 on 2019-11-07 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0059_auto_20191107_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_val',
            field=models.DateField(verbose_name='Date de Réunion'),
        ),
    ]
