# Generated by Django 2.2.6 on 2019-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0060_auto_20191107_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu'),
        ),
    ]
