# Generated by Django 2.2.6 on 2019-11-08 08:32

import bureau.sca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0061_auto_20191107_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingdoc',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='meetingdoc',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='file_cn',
            field=models.FileField(blank=True, null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='file_fr',
            field=models.FileField(blank=True, null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
    ]
