# Generated by Django 2.2.6 on 2019-11-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0062_auto_20191108_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingdoc',
            name='ref_no',
        ),
    ]
