# Generated by Django 2.2.6 on 2019-11-08 08:49

import bureau.sca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0063_remove_meetingdoc_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingitem',
            name='alias_cn',
        ),
        migrations.RemoveField(
            model_name='meetingitem',
            name='alias_fr',
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='file_cn',
            field=models.FileField(blank=True, help_text='version final en Chinois', null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='file_fr',
            field=models.FileField(blank=True, help_text='version final en Français', null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
    ]
