# Generated by Django 2.2.6 on 2019-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0064_auto_20191108_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='ref_no',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
    ]
