# Generated by Django 2.2.6 on 2019-11-08 11:05

import bureau.sca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0066_auto_20191108_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='file_cn',
            field=models.FileField(blank=True, help_text='version final en Chinois', null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='file_fr',
            field=models.FileField(blank=True, help_text='version final en Français', null=True, upload_to=bureau.sca.models.upload_path_handler),
        ),
    ]
