# Generated by Django 2.2.6 on 2019-11-13 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0068_auto_20191112_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='date_val',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du Sujet'),
            preserve_default=False,
        ),
    ]
