# Generated by Django 2.2.6 on 2020-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0069_meetingitem_date_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalfilestorage',
            name='chk_approv',
            field=models.BooleanField(default=False, help_text='2nd Agent', verbose_name='Appv'),
        ),
        migrations.AlterField(
            model_name='internalfilestorage',
            name='chk_verify',
            field=models.BooleanField(default=False, help_text='1st Agent', verbose_name='Verf'),
        ),
    ]
